### ISSUE TITLE
QUADS : Power control 

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/quads#100]
There have been multiple needs for "flea-power-drains", however some of these power-drains do not need the additional step of hitting the power button as we have recently found it. 

Not sure how far we want to take this work, or if all IP controllable power strips use a very similar API.

# High-level implementation details below: 

_Power abstract class -> Power Brand class_

Each Host object would have a attribute of a Power Brand class, which it can manipulate the power control.
**host.power("ip of strip","user","pass")** <-- Once this object is init() it will check the current status of the power -- store that int he host object -- then we can query how many hosts are turned on/off...
**host.power.reset()**
**host.power.off()**
**host.power.on()**
**host.power.drain()** <-- maybe have this be off w/ sleep(30), and then powered on.

**Comment by smalleni** [comment]
s/instance/attribute?

**Comment by sadsfae** [comment]
This is a good suggestion for inclusion into QUADS, particularly so because we try and only utilize vanilla ```ipmitool```.

**Comment by sadsfae** [comment]
This is needed for https://github.com/redhat-performance/quads/issues/13 per @jtaleric

**Comment by sadsfae** [comment]
related patchset WIP: https://review.gerrithub.io/#/c/371758/
