### ISSUE TITLE
Publish Docker Images for QUADS Wiki Component

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#102]
While we have [external-to-QUADS Ansible playbooks](https://github.com/redhat-performance/ops-tools/tree/master/ansible/wiki-wordpress-nginx-mariadb) it would be easier to consume if we provided a dockerized Wordpress/QUADS Wiki container.

This will contain:

- Wordpress (latest version)
- MariaDB
- nginx
- php-fm

**Comment by sadsfae** [comment]
Some more background here, we had been using [this Ansible playbook](https://github.com/redhat-performance/ops-tools/tree/master/ansible/wiki-wordpress-nginx-mariadb) to previously deploy the Wordpress stack.

In addition the following post-deployment steps need to be taken:

- Wordpress [Krusze](http://krusze.com/krusze/) theme (works well with markdown-generated tables)
- [JP Markdown](https://wordpress.org/plugins/jetpack-markdown/) plugin
- Some basic manipulation of the Wordpress "Menu" for machine inventory and assignments (see main wiki docs)

**Comment by grafuls** [comment]
I'd be happy to take this one

**Comment by sadsfae** [comment]
Testing / development location here prior to being reviewed and merged:

https://github.com/grafuls/wordpress-quads

**Comment by grafuls** [comment]
Current status of wordpress-quads repo:
- Solution is able to crate and link 2 containers.
  * 1 container for WP, PHP and nginx
  * 1 container for mariadb
- This is achieved with docker-compose which spawns the DB container first and waits for it to be on a "healthy" state before spawning the actual WP container.
- Initial admin user and pass is set automatically via WP cli
- WP theme Krusze is also applied via WP cli
- WP plugin JP Markdown is also applied via WP cli

TODOs:
- Couldn't figure out a way to override the WP welcome screen even after setup via WP cli
- Having troubles with docker-compose to run the initial setup scripts

**Comment by sadsfae** [comment]
This can be marked completed as of recent commits to `1.1` codebase, currently `master` branch.

Please see:  https://github.com/redhat-performance/quads/blob/master/CONTRIBUTING.md#quads-development-setup
