### ISSUE TITLE
RFE: Generate separate instackenv.json instead of adding to the existing one everytime hosts are added

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#104]
The request is to have a separate instackenv.json geenrated when hosts are added to the environment as this will help reduce complexity. The user has to separate out new hosts anyway as he wouldn't reintrospect ones that have already been deployed.

**Comment by smalleni** [comment]
@kambiz-aghaiepour

**Comment by sadsfae** [comment]
@smalleni where would you envision this going?  as-is it's simply replaced to update the current environment.

**Comment by sadsfae** [comment]
Closing this issue, we both generate new instackenv files but we also revision them too and keep older copies for a configurable period.
