### ISSUE TITLE
Need exclusive file locking.

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#109]
Under very rare circumstances it is possible for the schedule yaml data to be written out partially by one process, and before the process has a chance to completely write out the data in memory, another process will attempt to load the yaml data and take action.  Depending on if the partially written yaml data is consistent (but incomplete) this can yield unexpected results.

The fix would be to ensure there is an exclusive lock on the yaml data.  This should be done in both the read and write operations.

**Comment by sadsfae** [comment]
This needs to be implemented solely within the write functions, read() will cause blocking issues.
