### ISSUE TITLE
RFE:  Add pulldown menu to Request Tracker option

### ISSUE THREAD

**Issue by abondvt89** [redhat-performance/quads#11]
Once in the RT system you can search for various tags like [scale council] to see just the Scale Lab request tickets, but it would be useful to allow this view straight from the wiki menu.  Having it there would make the Request Tracker menu item much more user friendly.

So have a pulldown menu with maybe 3 options.

Scale Council Tickets
Issue Tickets
All Tickets

**Comment by sadsfae** [comment]
This is completed.
