### ISSUE TITLE
RFE: QUADs Assignment email doesn't reference ticket 

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#12]
It would be nice to have the assignment email that is automatically sent once the QUADs allocates the new environment to include the RT ticket number and also have the ticket updated about the assignment.

**Comment by sadsfae** [comment]
Hey @smalleni the assignments page lists the ticket, is this not sufficient?  If not we can probably add this.

**Comment by smalleni** [comment]
@sadsfae Yes I think it would be useful to reference the ticket and also update the ticket with the QUADs assignment email.

**Comment by sadsfae** [comment]
This is mostly addressed here now:

https://github.com/redhat-performance/quads/commit/1bd60a72e67a37660f355e463ea8cfe18f8cf5eb
