### ISSUE TITLE
RFE: Make QUADs give user a fully built TripleO cloud with the machine assignment

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#13]
It would be cool if the user had an option to specify the version/puddle/build of TripleO/Director he wanted in the ticket and QUADs hands him over the fully baked cloud with browbeat installed. I'm sure we can integrate Justin's work with what we already have in QUADs to make this work.

**Comment by sadsfae** [comment]
Adding priority flag as we are aiming to have this completed, fully tested and integrated prior to July when the 30 x or so machines are shipping down from Boston.

**Comment by sadsfae** [comment]
After a lot of consideration to include the scope of QUADS and our development resources we will not be expanding our capabilities to perform tenant automation/deployment.  It's just beyond what we can handle, instead it's better for tenants to utilize the APIv3 that is now available [with QUADS 2.0](https://github.com/redhat-performance/quads/releases/tag/v2.0.0) to perform their own automation.

The most we can extend beyond this is sending webhooks on release of an environment if that's useful too (to perhaps an Ansible Tower/AAC somewhere?) covered in  https://github.com/redhat-performance/quads/issues/417 but with APIv3 this really isn't needed either if you just poll the API.
