### ISSUE TITLE
support NIC teaming

### ISSUE THREAD

**Issue by bengland2** [redhat-performance/quads#132]
IN order to use fewer workload generator, or client-class, or compute node machines to drive load to storage servers in scale lab, it would be nice to support NIC teaming as a networking option instead of just having a separate VLAN & subnet for every physical NIC port.   This could be useful for Ceph , Gluster, NFS , SMB and iSCSI workloads involving sequential I/O, where network bandwidth is usually a bottleneck.   I don't know how to request that right now, Will Foster suggested creating an issue and tagging it appropriately so I'm trying.

Sanjay Rao and I measured in RHEL 7.3 that NIC bonding, unlike NIC teaming, does not increase interface throughput past a single NIC port's capacity.  

The big question is mode to use with NIC teaming.  Everyone agrees that LACP gives best load balancing on inbound network traffic, and balance-alb does not work in all cases, but LACP also requires that switches all support that and are appropriately configured, unlike other modes.  So perhaps we should provide some choices here and let people experiment a bit and see what works for them.  Best-performing modes are typically bonding modes 2 (balance-xor, xmit_hash_policy=level3+4), 4 (lacp), and 6 (balance-alb).

**Comment by sadsfae** [comment]
Hey @bengland2 thanks for filing this.  Today we would be able to support any level of teaming on the client-side only that doesn't require switchport changes.  For this we'd employ the ```qinq: 1``` configuration documented here:

https://github.com/redhat-performance/quads/blob/master/README.md#creating-a-new-cloud-assignment-and-schedule

This occurs when the assignment is defined, prior to it being deployed so if you'd like to test with this just let us know prior to your next deployment.

To support other bonding modes that would require switchport changes we can certainly look to implement this in the same fashion with an option set prior to deployment.  Let's mark this with a 1.1 milestone for the latter, and you can test with the former for a future assignment.

**Comment by bengland2** [comment]
Great! I'm happy with this for now, let's see if we can get both NIC ports cranking using just the non-LACP bonding modes, if this doesn't work I'll get back to you.

**Comment by sadsfae** [comment]
Catching up on this, this can be accomplished today by specifying qinq 1 VLAN mode (all interfaces on the same VLAN) and just setting up Linux bonding on the client side across two more more interfaces.  Would this satisfy your requirement?

https://github.com/redhat-performance/quads#quads-vlan-options

**Comment by sadsfae** [comment]
Closing and archiving this.  If it needs to be revisited we can re-open.
