### ISSUE TITLE
RFE: Have QUADs build an OpenStack cloud every weekend from remaining machines and have Browbeat run against it

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#14]
After all the assignments, there could be a few machines idle and it would be awesome if QUADs can grab these machines, build a cloud with it, record machine configs as metadata and push the results to ES using Browbeat.

**Comment by sadsfae** [comment]
This has been brought up again and we've discussed our approach here.  We're nearing the point I think we can start working to implement this.  We'll want to have a set of fairly static machines which can be optionally used for this if they are not in a current allocation for starters (and also has a sane, repeatable OSP design in terms of roles.)

The playbooks and Heat templates you and team have created per-machine type will really help here.

**Comment by sadsfae** [comment]
Update here: we have 9 x Dell r620's and a new switch in rack b08 to start testing this with.

**Comment by sadsfae** [comment]
After a lot of consideration to include the scope of QUADS and our development resources we will not be expanding our capabilities to perform tenant automation/deployment.  It's just beyond what we can handle, instead it's better for tenants to utilize the APIv3 that is now available [with QUADS 2.0](https://github.com/redhat-performance/quads/releases/tag/v2.0.0) to perform their own automation.

The most we can extend beyond this is sending webhooks on release of an environment if that's useful too (to perhaps an Ansible Tower/AAC somewhere?) covered in  https://github.com/redhat-performance/quads/issues/417 but with APIv3 this really isn't needed either if you just poll the API.
