### ISSUE TITLE
Move from SimpleHTTPServer to CherryPy

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#140]
Using SimpleHTTPServer simple wsgi Python libraries was good enough for a bare-bones JSON API but we're really hitting the constraints of it.

Sooner than later we need to dropship everything [CherryPy](https://cherrypy.org/).  This also paves the way for having a proper self-service / UI as well.

Some basic, immediate benefits would be:

- integrated unit testing support
- RESTful request dispatching
- uses Jinja2 templating
- varied ODM integration
- thread pooling
- sessions, authentication

The following bug fixes or issue are evident of this need:

https://github.com/redhat-performance/quads/issues/109
https://github.com/redhat-performance/quads/issues/139
https://github.com/redhat-performance/quads/issues/22

**Comment by sadsfae** [comment]
Adding some more detail here, this will ultimately pave the way for a gen-2.0 architecture to include:

* Replacing cron and all event-driven actions with celery
* Replace flat-file struction with sqlite
* Replace ```schedule.yml``` with sqlite

I have created a 2.0 milestone RFE here:

https://github.com/redhat-performance/quads/issues/156

**Comment by geekodour** [comment]
@sadsfae I would like to work on this,
regarding issues #109, #139, #22 . 

As far as I can see the SimpleHTTPServer implemented in ` bin/quads-daemon` so in the forked branch have to start from the here right?

Also for #156 (Migrating to celery) this has to be implemented first, i guess?

**Comment by sadsfae** [comment]
Hey @geekodour we'd ideally do this in manageable stages across several fronts but it will most likely look like this:

- Move from SimpleHTTPServer to Flask - Milestone 1.1
- Move from flat-file management to sqllite - Milestone 1.1
- Create a quads-ng branch and work on moving to a gen 2.0 architecture
   * Move to celery / rabbitMQ type backend
   * Have a working, functional Flask UI with auth & feature parity with ```quads-cli```
- quads-ng becomes the new master branch Milestone 2.0
- old master branch becomes quads-legacy

There's a few individual RFE's open as well as milestones mapped to cover all of this.  It will be quite an undertaking so it's easier to tackle in phases.

**Comment by sadsfae** [comment]
This is completely implemented now in the `1.1` codebase, which is currently the `master` branch.
