### ISSUE TITLE
RFE:  Ticket based QUADS query

### ISSUE THREAD

**Issue by abondvt89** [redhat-performance/quads#148]
Add the ability to query QUADS based on the ticket number for the following information for past, current, and future allocations.

* Start date
* End date
* Number of machines in the allocation by machine type

**Comment by sadsfae** [comment]
We might look at something like plotly? @kambiz-aghaiepour  https://plot.ly/python/heatmaps/

Ideally this would need to be able to be packaged in RPM however.

**Comment by QuantumPosix** [comment]
#105 Follow up - our visualization is currently using plotly @sadsfae

**Comment by sadsfae** [comment]
We can query what cloud description / cloud existed based on the date using the `-d YYYY-MM-DD HH:MM` format with the `-d` or `--datetime` argument but it does not correlate the current `--cloud-ticket` of that cloud at the time.

(current display)
```
# /opt/bin/quads-cli --full-summary 
cloud01 : 3 (Available servers)
cloud02 : 0 (Storage DFG RHCS 1 of 2)
cloud03 : 49 (OpenShift Scale CI)
```

(Query against a date - 2018-04-04 22:00)
```
# /opt/quads/bin/quads --full-summary --date "2018-04-04 22:00"
cloud01 : 12 (Available servers)
cloud02 : 0 (RHCS Spectre/Meltdown)
cloud03 : 47 (OpenShift Scale CI)
```
However, `--ls-ticket` does not get queried when passing the `-d` or `--datetime` argument - this needs to be changed:

(date in future, still shows current `--cloud-ticket` mappings)
```
# quads --ls-ticket --datetime "2018-04-04 22:00" | head -n 3
cloud02: 470086
cloud03: 470816
```

(current display)
[root@walkabout ~]# quads --ls-ticket | head -n 3
cloud02: 470086
cloud03: 470816
```

**Comment by sadsfae** [comment]
Adding this to the 2.0 roadmap, though it's going to be a less priority than some of the other RFEs.

I think this is possible by some additional methods using only the data already available in QUADS, but note that the current usage of `--cloud-ticket` is transient/temporal in that it gets reset when that environment gets re-purposed at some other point.

**Comment by grafuls** [comment]
This can be achieved with the new REST api like this:
```
$ curl http://{QUADS_SERVER}/api/v3/assignments?ticket=3804
```
From this result you can get the assignment id to then pass it to the schedule query:
```
$ curl http://{QUADS_SERVER}/api/v3/schedules?assignment_id=30
```
