### ISSUE TITLE
allow the use of textures in visualizations

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#151]
The visualizations use simple colors.  It would be nice to be able to represent the clouds using texture image files as opposed to simple colors (currently using html td attribute "bgcolor".  It should be simple to use "background" attribute.

**Comment by sadsfae** [comment]
This is a nice feature to add +1.

**Comment by sadsfae** [comment]
Let's make this so we're keeping these in ```conf/quads.yml```
