### ISSUE TITLE
Understanding quads code-flow for adding hosts in quads from HIL

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#171]
I am currently working on the integration of nodes from HIL that can be registered with quads.

Trying to understand the code -- correct if I have got it wrong. 

handling host additions 
```
 quads-cli (makes api calls)  --> quads-daemon (which runs a web server) 
--> (missing pieces.. are any other /bin/files involved ? )  --> writes a file per host under /opt/quads/data/system 
```

I want to know:  
how can I run the quads-daemon in the foreground so that I can debug the code ?
what is the code flow that adds the new hosts to the quads system ?

**Comment by sadsfae** [comment]
Hey @SahilTikale quads-daemon is just a Python SimpleHTTPServer wsgi application that listens on a pre-defined port.

If you look at the installation docs here for the Git installation you can run it and see all the verbosity but we generally recommend the RPM installation method most of the time:

https://github.com/redhat-performance/quads#installing-quads

Besides the daemon / cli that makes JSON API calls there's also an assortment of small utilities under ```/opt/quads/bin``` that help with provisioning, wiki creation/updates, validation and other allocation related things but these don't have anything to do with the core scheduling functionality.

In general QUADS manages these file structures:

```/opt/quads/data/schedule.yaml```  This is the main cloud and host scheduling file that is managed by QUADs.

```/opt/quads/data/state/host-fqdn-or-hostname-here```  This is a state directory, in it there is a flat file per QUADS-managed host that contains the current cloud it should belong to.  This is queried via cron and if it differs from it's current state it will be moved.

Running the quads sandbox script will get you a fully working environment and auto-create a few dummy hosts and clouds:

https://github.com/redhat-performance/quads/blob/master/testing/quads-sandbox.sh

I hope this helps, we can available to talk in more detail about this or update things here in a more specific manner depending on any questions you have.

**Comment by SahilTikale** [comment]
Thank you @sadsfae your explanation helped me in setting up a dev-environment for QUADS.
I am exploring the `move-hosts` command. I will ask more questions once have a better understanding of what it does or rather what I do not understand. (Please excuse the oxymoron :) )
