### ISSUE TITLE
instackenv.json included undercloud machine

### ISSUE THREAD

**Issue by akrzos** [redhat-performance/quads#172]
The instackenv provided from quads contained all nodes (16 out of 16 nodes) in the allocated cloud rather than just the "overcloud" nodes that the instackenv.json should contain.

**Comment by sadsfae** [comment]
I believe this is an edge case when the first machine was removed from the assignment after it already went out (as this is usually the undercloud by default).

A workaround here is to just set ```nullos: false``` in Foreman host parameter for that host to remove it from instackenv.json management.  I think we should cover this edge case however so thanks for reporting it.

**Comment by grafuls** [comment]
This has been resolved and nullos replaced with "overcloud" parameter under Foreman. First host will always be excluded from instack json and whenever we set the overcloud parameter to False in Foreman, these will also be excluded from the json.
https://review.gerrithub.io/c/redhat-performance/quads/+/449568
