### ISSUE TITLE
How does the ownership work in QUADS ?

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#173]
I see in the `schedule.yaml` that clouds have the `owner: ` field but the hosts do not have any such field.

What is the notion of ownership in QUADS. I am trying to understand and relate it to [HIL](https://github.com/SahilTikale/hil)

- Do users own clouds ? and clouds means single network to which hosts are connected ?
- Is the mapping of users to cloud unique ? Do you recycle the clouds between different users. 

I remember some talk about reusing same cloud names between users.  

- How do you ensure that two users do not inadvertently become owner of the same cloud ?
- Is there a notion of multiple users owning a cloud ?

**Comment by sadsfae** [comment]
Hey @SahilTikale:

Ownership is based on the ```--cloud-owner``` setting of the cloud that the machine(s) belong at that point in time or during the ```--schedule-start``` and ```--schedule-end``` dates.

Ownership is set by ownership of the cloud, not by the servers that belong to it.

Each cloud can only have one ```--cloud-owner``` but it can have multiple ```--cc-users``` which are just users that receive the notification emails.

There is not a notion of multiple owners per cloud.  Users as it pertains to cloud ownership are just free-form strings so they could be a groupname, department name etc but they should contain an email address (or alias with domain) for notification purposes if you intend to use those.

This is configurable here:

https://github.com/redhat-performance/quads/blob/master/conf/quads.yml#L10

If you wanted to forgo notifications that's also configurable:

https://github.com/redhat-performance/quads/blob/master/conf/quads.yml#L26
