### ISSUE TITLE
How does networking work in QUADS

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#176]
I am collecting multiple questions under this issue as they are related.

- In the `/data/schedule.yaml` file whenever I add a host I see a field `interfaces: {}`
what is the purpose of it. I could not find any working example that uses it. neither cli has any way of inserting values into it. Please elaborate.

- In documentation related to [host-port to switch-interface](https://github.com/SahilTikale/quads/blob/master/docs/switch-host-setup.md#quads-host-network-setup) I understand that the mappings are stored in a flat file `/opt/quads/data/ports/<hostname>`
When and how is it used ? I could not find documentation related to it. 

- Explanation about QinQ and how it relates to clouds in QUADS is not clear. 

- When a schedule is set up and nodes are moved between clouds, how to check if the hosts are moved to correct vlans ? 

If these are too many questions for a single issue, let me know I will make separate issues for each one.

**Comment by sadsfae** [comment]
>      In the /data/schedule.yaml file whenever I add a host I see a field interfaces: {}
>     what is the purpose of it. I could not find any working example that uses it. neither cli has any way of inserting values into it. Please elaborate.

I believe this is a stub and not currently used anywhere.  @kambiz-aghaiepour could probably elaborate more on the intentions.

>     In documentation related to host-port to switch-interface I understand that the mappings are stored in a flat file /opt/quads/data/ports/<hostname>
>     When and how is it used ? I could not find documentation related to it.

See: https://github.com/redhat-performance/quads/blob/master/docs/switch-host-setup.md#quads-host-network-setup host and network setup docs.

It's used by expect to parse for the correct switch, interface and switchport to change for moving things.

You can see this used here:

https://github.com/redhat-performance/quads/blob/master/bin/move-and-rebuild-host.sh#L114


>     Explanation about QinQ and how it relates to clouds in QUADS is not clear.

Q-in-Q VLANS are just a JunOS construct, we currently support two designs explained here:

https://github.com/redhat-performance/quads#quads-vlan-options  Let me know what parts of that need further explanation.

>     When a schedule is set up and nodes are moved between clouds, how to check if the hosts are moved to correct vlans ?

We perform validations for system and network, for the network this is called here:

https://github.com/redhat-performance/quads/blob/master/bin/quads-validate-env.sh#L103

It utilizes this tool here:

https://github.com/redhat-performance/quads/blob/master/bin/quads-post-network-test.sh

We also provide a tool to verify the configuration is right (and optionally fix it) on the switch side here:

https://github.com/redhat-performance/quads/blob/master/bin/quads-verify-switchconf.sh

> If these are too many questions for a single issue, let me know I will make separate issues for each one.

No problem, works for us.
