### ISSUE TITLE
IPMI information about hosts

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#177]
Where are the IPMI credentials for each host stored.
Are they all same for all machines and stored in the `quads.yml`
What scripts use them ?

HIL proxies all IPMI calls hence I will need to modify this scripts.

**Comment by sadsfae** [comment]
> Where are the IPMI credentials for each host stored.
> Are they all same for all machines and stored in the quads.yml
> What scripts use them ?

IPMI credentials are defined here:

https://github.com/redhat-performance/quads/blob/master/conf/quads.yml#L97

We use a separate ```quads``` user that has its password changed per cloud environment for the lifetime of that current assignment.  Currently this is the RT ticket number associated with that request (e.g. there's only one quads user but the password is different per environment)

We also define credentials here for our Ansible boot order playbooks (SuperMicro only, as we use racadm for Dell boot order changes).

https://github.com/redhat-performance/quads/blob/master/ansible/ipmi_credentials.yml

Boot order playbooks are really only to help accomodate OpenStack Triple-O/Director deployments as it requires a special interface order and PXE enablement.

**Comment by sadsfae** [comment]
Here's some more documentation around how the Ansible boot order playbooks work in `1.0` that have been added recently.  I think this combined with the previous info above you should be set:

https://github.com/redhat-performance/quads/tree/1.0/ansible#ansible-boot-order-playbooks-for-dell-systems
