### ISSUE TITLE
Using --force in --define-hosts does not update the values in schedule.yaml

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#178]
eg. 
I add a host 
```
$quads_cmd --define-host interface_node00 --default-cloud cloud01 --host-type vendor_abc --host-interface --allocator HIL
```

It gets added successfully.

If I have to update the values say like 
```
$quads_cmd --define-host interface_node00 --default-cloud cloud07 --host-type changed_vendor --host-interface --allocator HIL --force
```

It does not update the values in schedule.yaml.
If I delete the host entry and then send the first command then it works with new info. 

Was wondering if I am missing anything.

**Comment by kambiz-aghaiepour** [comment]
When I use the sandbox environment based on master, it in fact does the right thing.  For example:

[kambiz@loki (master)]$ /tmp/quadsCqkV/quads/bin/quads-cli --define-host host05.example.com --host-type fake --default-cloud cloud01
127.0.0.1 - - [13/Jun/2018 09:16:28] "POST /api/v1/host HTTP/1.1" 200 -
OK

[kambiz@loki (master)]$ tail -5 /tmp/quadsCqkV/quads/data/schedule.yaml
  host05.example.com:
    cloud: cloud01
    interfaces: {}
    schedule: {}
    type: fake

[kambiz@loki (master)]$ /tmp/quadsCqkV/quads/bin/quads-cli --define-host host05.example.com --host-type fake2 --default-cloud cloud01
127.0.0.1 - - [13/Jun/2018 09:18:16] "POST /api/v1/host HTTP/1.1" 200 -
Host "host05.example.com" already defined. Use --force to replace

[kambiz@loki (master)]$ /tmp/quadsCqkV/quads/bin/quads-cli --define-host host05.example.com --host-type fake2 --default-cloud cloud01 --force
127.0.0.1 - - [13/Jun/2018 09:18:28] "POST /api/v1/host HTTP/1.1" 200 -
OK

[kambiz@loki (master)]$ tail -5 /tmp/quadsCqkV/quads/data/schedule.yaml
  host05.example.com:
    cloud: cloud01
    interfaces: {}
    schedule: {}
    type: fake2


Perhaps if you've introduced new data structures, there is some missing logic to ensure the new data structures get updated with --force?  Do you have a gerritt WIP review I can look at?
