### ISSUE TITLE
"New QUADS Assignment Allocated" notification

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#181]
The notification email that gets sent out looks something like, 
```
Greetings Citizen,

A new future environment has been allocated for you in the system!
This means that sometime in the future you'll be given a working
schedule and Scale Lab assignment that will belong inside this
unique environment.

cloud20 : 0 (OSP DevConf)
```

I realize it ssays 0 hosts because the environment hasn't yet been provisioned but this might be confusing to folks reading the email. Is there a way to include the correct number of hosts scheduled to mov into the cloud at the start of assignment?

**Comment by smalleni** [comment]
@kambiz-aghaiepour  @sadsfae  @abondvt89

**Comment by sadsfae** [comment]
There's no way to know this information because the hosts haven't been scheduled yet, the most that can happen is to remove the number entirely.  This occurs when the cloud definition is set, but always prior to when any number of hosts may be added.

**Comment by kambiz-aghaiepour** [comment]
https://review.gerrithub.io/#/c/redhat-performance/quads/+/418220

should address this.
