### ISSUE TITLE
Cleanup validation networks created by QUADS before environment handoff

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#183]
Any reason/technical difficulties to not delete the validation networks/ips assigned to backend host interfaces during network validation and hand the user a clean environment after validation?

@kambiz-aghaiepour  @sadsfae @jtaleric @abondvt89

**Comment by smalleni** [comment]
I would prefer to not have my host networking in this state when I get the environment:

[root@c08-h17-r930 ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: em3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:6c brd ff:ff:ff:ff:ff:ff
    inet 10.12.70.17/23 brd 10.12.71.255 scope global em3
       valid_lft forever preferred_lft forever
    inet6 2620:52:0:c46:266e:96ff:fe0d:3f6c/64 scope global mngtmpaddr dynamic
       valid_lft 2591794sec preferred_lft 604594sec
    inet6 fe80::266e:96ff:fe0d:3f6c/64 scope link
       valid_lft forever preferred_lft forever
3: em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:68 brd ff:ff:ff:ff:ff:ff
    inet 172.16.70.17/16 brd 172.16.255.255 scope global em1
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f68/64 scope link
       valid_lft forever preferred_lft forever
4: em4: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 24:6e:96:0d:3f:6d brd ff:ff:ff:ff:ff:ff
5: em2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:6a brd ff:ff:ff:ff:ff:ff
    inet 172.17.70.17/16 brd 172.17.255.255 scope global em2
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f6a/64 scope link
       valid_lft forever preferred_lft forever
6: p1p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:36:9f:98:44:d8 brd ff:ff:ff:ff:ff:ff
    inet 172.18.70.17/16 brd 172.18.255.255 scope global p1p1
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44d8/64 scope link
       valid_lft forever preferred_lft forever
7: p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a0:36:9f:98:44:da brd ff:ff:ff:ff:ff:ff
    inet 172.19.70.17/16 brd 172.19.255.255 scope global p1p2
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44da/64 scope link
       valid_lft forever preferred_lft forever
8: em1.101@em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:68 brd ff:ff:ff:ff:ff:ff
    inet 172.20.70.17/16 brd 172.20.255.255 scope global em1.101
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f68/64 scope link
       valid_lft forever preferred_lft forever
9: em1.200@em1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:68 brd ff:ff:ff:ff:ff:ff
    inet 172.24.70.17/14 brd 172.27.255.255 scope global em1.200
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f68/64 scope link
       valid_lft forever preferred_lft forever
10: em2.102@em2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:6a brd ff:ff:ff:ff:ff:ff
    inet 172.21.70.17/16 brd 172.21.255.255 scope global em2.102
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f6a/64 scope link
       valid_lft forever preferred_lft forever
11: em2.200@em2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 24:6e:96:0d:3f:6a brd ff:ff:ff:ff:ff:ff
    inet 172.25.70.17/14 brd 172.27.255.255 scope global em2.200
       valid_lft forever preferred_lft forever
    inet6 fe80::266e:96ff:fe0d:3f6a/64 scope link
       valid_lft forever preferred_lft forever
12: p1p1.103@p1p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a0:36:9f:98:44:d8 brd ff:ff:ff:ff:ff:ff
    inet 172.22.70.17/16 brd 172.22.255.255 scope global p1p1.103
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44d8/64 scope link
       valid_lft forever preferred_lft forever
13: p1p1.200@p1p1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a0:36:9f:98:44:d8 brd ff:ff:ff:ff:ff:ff
    inet 172.26.70.17/14 brd 172.27.255.255 scope global p1p1.200
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44d8/64 scope link
       valid_lft forever preferred_lft forever
14: p1p2.104@p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a0:36:9f:98:44:da brd ff:ff:ff:ff:ff:ff
    inet 172.23.70.17/16 brd 172.23.255.255 scope global p1p2.104
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44da/64 scope link
       valid_lft forever preferred_lft forever
15: p1p2.200@p1p2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether a0:36:9f:98:44:da brd ff:ff:ff:ff:ff:ff
    inet 172.27.70.17/14 brd 172.27.255.255 scope global p1p2.200
       valid_lft forever preferred_lft forever
    inet6 fe80::a236:9fff:fe98:44da/64 scope link
       valid_lft forever preferred_lft forever
16: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:bb:0e:d9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
17: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:bb:0e:d9 brd ff:ff:ff:ff:ff:ff
18: external: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:ca:fa:2c brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/16 brd 10.0.255.255 scope global external
       valid_lft forever preferred_lft forever
    inet6 2620:52:0:13b8::fe/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:feca:fa2c/64 scope link
       valid_lft forever preferred_lft forever
19: external-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master external state DOWN group default qlen 1000
    link/ether 52:54:00:ca:fa:2c brd ff:ff:ff:ff:ff:ff
20: data: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:3e:06:82 brd ff:ff:ff:ff:ff:ff
    inet 192.168.24.254/24 brd 192.168.24.255 scope global data
       valid_lft forever preferred_lft forever
21: data-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master data state DOWN group default qlen 1000
    link/ether 52:54:00:3e:06:82 brd ff:ff:ff:ff:ff:ff

**Comment by smalleni** [comment]
Infrared (https://github.com/redhat-openstack/infrared) can create a scale OSP deployment on a single hypervisor by creating ZVMs, virsh networks etc. Sometimes, it would be good for us to recognize that the automation people run against scale lab machines creates its own network that might conflict with what you already have. In my case, infrared is trying to create virsh networks on the hypervisor that conflict with what QUADS lays down.

.24.254', u'name': u'data'}, 'key': u'net1'})\u001b[0m", "", "TASK [check if network is active] **********************************************", "\u001b[0;33mchanged: [hypervisor] => (item={'value': {u'name': u'external', u'floating_ip': {u'start': u'10.0.127.1', u'end': u'10.0.255.254'}, u'external_connectivity': True, u'netmask': u'255.255.0.0', u'ipv6': {u'dhcp': {u'range': {u'start': u'2620:52:0:13b8::fe:1', u'end': u'2620:52:0:13b8::fe:ff'}}, u'prefix': u'64', u'ip_address': u'2620:52:0:13b8::fe'}, u'forward': u'nat', u'dhcp': {u'range': {u'start': u'10.0.0.2', u'end': u'10.0.127.254'}, u'subnet_cidr': u'10.0.0.0/16', u'subnet_gateway': u'10.0.0.1'}, u'ip_address': u'10.0.0.1'}, 'key': u'net3'})\u001b[0m", "\u001b[0;31mfailed: [hypervisor] (item={'value': {u'name': u'management', u'floating_ip': {u'start': u'172.16.128.1', u'end': u'172.16.255.254'}, u'external_connectivity': True, u'netmask': u'255.255.0.0', u'forward': u'nat', u'dhcp': {u'range': {u'start': u'172.16.0.2', u'end': u'172.16.127.254'}, u'subnet_cidr': u'172.16.0.0/16', u'subnet_gateway': u'172.16.0.1'}, u'ip_address': u'172.16.0.1'}, 'key': u'net2'}) => {\"changed\": false, \"item\": {\"key\": \"net2\", \"value\": {\"dhcp\": {\"range\": {\"end\": \"172.16.127.254\", \"start\": \"172.16.0.2\"}, \"subnet_cidr\": \"172.16.0.0/16\", \"subnet_gateway\": \"172.16.0.1\"}, \"external_connectivity\": true, \"floating_ip\": {\"end\": \"172.16.255.254\", \"start\": \"172.16.128.1\"}, \"forward\": \"nat\", \"ip_address\": \"172.16.0.1\", \"name\": \"management\", \"netmask\": \"255.255.0.0\"}}, \"msg\": \"internal error: Network is already in use by interface em1\"}\u001b[0m", "\u001b[0;33mchanged: [hypervisor] => (item={'value': {u'external_connectivity': False, u'netmask': u'255.255.255.0', u'ip_address': u'192.168.24.254', u'name': u'data'}, 'key': u'net1'})\u001b[0m", "", "NO MORE HOSTS LEFT *************************************************************", "\tto retry, use: --limit @/Users/smalleni/Documents/test/infrared/plugins/virsh/main.retry", "", "PLAY RECAP *********************************************************************", "\u001b[0;31mhypervisor\u001b[0m                 : \u001b[0;32mok=44  \u001b[0m \u001b[0;33mchanged=19  \u001b[0m unreachable=0    \u001b[0;31mfailed=1   \u001b[0m", "\u001b[0;33mlocalhost\u001b[0m                  : \u001b[0;32mok=3   \u001b[0m \u001b[0;33mchanged=3   \u001b[0m unreachable=0    failed=0   "]}


The automation fails because of this. I think some users need clean hosts, although many might get use of what you already lay down.

**Comment by sadsfae** [comment]
@kambiz-aghaiepour had a good solution for saving you an rm command to remove the network configs on your undercloud by dropping down a cleanup script to remove them for you.

For everyone else not doing openstack these configs are very useful (and are also needed for our validations).

I concur with this approach if having to remove the network configs on your undercloud host is a hindrance e.g. run a script versus run an rm command.

**Comment by kambiz-aghaiepour** [comment]
The next time we install a host via foreman, you should find the cleanup script in /root/cleanup.sh

You can run it as:

   /root/cleanup.sh --disable

or 

  /root/cleanup.sh --nuke

to either down the interfaces, and set ONBOOT=no, or to down the interfaces and completely remove the config files.

Kambiz

**Comment by sadsfae** [comment]
This is the code:

```
#!/bin/sh
#
# Cleanup validation interface configs
#

# print usage if not specified
if [[ $# -eq 0 ]]; then
        echo "USAGE:" 
        echo "       ./cleanup.sh --disable"
	echo "       ./cleanup.sh --nuke"
	exit 1
fi

mode=$1
disable=false
nuke=false

if [ "$mode" == "--disable" ]; then
  disable=true
fi

if [ "$mode" == "--nuke" ]; then
  nuke=true
fi

filelist="$(grep IPADDR=172 /etc/sysconfig/network-scripts/* | awk -F: '{ print $1 }')"

if $disable ; then
  for f in $filelist ; do
    ifdown $(basename $f | awk -F- '{ print $2 }')
    sed -i -e 's/ONBOOT=yes/ONBOOT=no/g' $f
  done
fi

if $nuke ; then
  for f in $filelist ; do
    ifdown $(basename $f | awk -F- '{ print $2 }')
    rm -f $f
  done
fi

[
```

**Comment by smalleni** [comment]
@sadsfae Has this code been merged? I ask because the issue has been closed.

**Comment by sadsfae** [comment]
Yes, it does not live in QUADS but instead in our Foreman provisioning templates.

**Comment by smalleni** [comment]
Thanks for confirming.

**Comment by sadsfae** [comment]
You'll need to reprovision a machine for it to land or you can also pull it down here, it will be called `/root/cleanup-interfaces.sh`

https://github.com/redhat-performance/ops-tools/blob/master/misc-tools/clean-interfaces.sh

**Comment by smalleni** [comment]
@sadsfae @kambiz-aghaiepour @abondvt89 

The script placed on my host was 
```
[root@c08-h17-r930 ~]# cat clean-interfaces.sh
#!/bin/sh
#
# Cleanup validation interface configs
#
#
# --nuke = remove interface files completely
# --disable = just stop them from starting at boot

if [[ 0 -eq 0 ]]; then
        echo "USAGE:"
        echo "./clean-interfaces.sh --disable"
	    echo "./clean-interfaces.sh --nuke"
	    exit 1
fi


mode=
disable=false
nuke=false

if [ "" == "--disable" ]; then
  disable=true
fi

if [ "" == "--nuke" ]; then
  nuke=true
fi

filelist="/etc/sysconfig/network-scripts/ifcfg-em1
/etc/sysconfig/network-scripts/ifcfg-em1.101
/etc/sysconfig/network-scripts/ifcfg-em1.200
/etc/sysconfig/network-scripts/ifcfg-em2
/etc/sysconfig/network-scripts/ifcfg-em2.102
/etc/sysconfig/network-scripts/ifcfg-em2.200
/etc/sysconfig/network-scripts/ifcfg-p1p1
/etc/sysconfig/network-scripts/ifcfg-p1p1.103
/etc/sysconfig/network-scripts/ifcfg-p1p1.200
/etc/sysconfig/network-scripts/ifcfg-p1p2
/etc/sysconfig/network-scripts/ifcfg-p1p2.104
/etc/sysconfig/network-scripts/ifcfg-p1p2.200"

if  ; then
  for f in  ; do
    ifdown
    sed -i -e 's/ONBOOT=yes/ONBOOT=no/g'
  done
fi

if  ; then
  for f in  ; do
    ifdown
    rm -f
  done
fi
```
Obviously this doesn't work. Seems to quite different from what you posted here, maybe some templating error in foreman?

**Comment by smalleni** [comment]
@h4xr Do you find this sort of IP/network laydown on your hosts useful? I think there were some comment made yesterday about "satellite" folks finding it useful. Can you comment and confirm.

**Comment by smalleni** [comment]
@psuriset

**Comment by h4xr** [comment]
@smalleni 
For satellite allocations, we mostly reconfigure the networking setup with our automation script(https://github.com/redhat-performance/satperf/blob/master/playbooks/common/roles/scalelab-nic-cleanup/tasks/main.yaml) to be more inline for our specific usecases. This automation usually cleans up the NICs providing us private IPs.
For public IP allocations, we usually request them as needed.

**Comment by smalleni** [comment]
@h4xr Thanks for confirming!

**Comment by sadsfae** [comment]
I'm closing this now, a resolution is in place, there is a script `clean-interfaces.sh` that lands in /root on every newly provisioned machine now.  @smalleni for your sat examples above, there's a difference between simply wiping out the interface configs (which anyone can now do) and redoing them to use a /8 instead of a /16.

While that's fine (and doubly so if a /8 is really needed) be aware using such a large broadcast domain can sometimes cause floods with broadcast domain traffic if you really don't need the associated `16777214` hosts/net that come with a /8 and instead `65534` hosts/net or less might suffice.
