### ISSUE TITLE
QUADS should have a dedicated "update" call for updating objects

### ISSUE THREAD

**Issue by SahilTikale** [redhat-performance/quads#185]
Currently, we use the `--force` option to update attributes of the `host` and the `cloud` objects.
for example to define a cloud we would use the following command:
```
$quads_cmd --define-cloud cloud02  --description "something for cloud 02"
```
and if I wish to later update the cloud attribute to have a cc-user or owner I have to do:

```
$quads_cmd --define-cloud cloud02  --description "something for cloud 02" --cc-users Alice --force
```
If I forget to add the `--description`, update operation will fail stating as error message that 

```
Missing required parameter: description
```

I feel users should be able to update the objects by stating only those attributes that require updating as follows:

```
$quads_cmd --update-cloud cloud02  --cc-users Alice
```
If maintainers agree with this issue, I will make a PR to [QUADS1.1](https://github.com/radez/quads/tree/cherrypy)

**Comment by SahilTikale** [comment]
@sadsfae @kambiz-aghaiepour any suggestions.

**Comment by sadsfae** [comment]
> Currently, we use the `--force` option to update attributes of the `host` and the `cloud` objects.
> for example to define a cloud we would use the following command:
> 
> ```
> $quads_cmd --define-cloud cloud02  --description "something for cloud 02"
> ```
> 
> and if I wish to later update the cloud attribute to have a cc-user or owner I have to do:
> 
> ```
> $quads_cmd --define-cloud cloud02  --description "something for cloud 02" --cc-users Alice --force
> ```
> 
> If I forget to add the `--description`, update operation will fail stating as error message that
> 
> ```
> Missing required parameter: description
> ```
> 
> I feel users should be able to update the objects by stating only those attributes that require updating as follows:
> 
> ```
> $quads_cmd --update-cloud cloud02  --cc-users Alice
> ```
> 
> If maintainers agree with this issue, I will make a PR to [QUADS1.1](https://github.com/radez/quads/tree/cherrypy)

Hey @SahilTikale sorry we didn't reply to this earlier.  This would be a useful addition.  I think we were purposely over-conservative with allowing `--define-cloud` operations so that once it's set it's set (you can sort of cheat and edit the yaml schedule directly for cloud metadata updates but that's not ideal).

**Comment by sadsfae** [comment]
In the latest `1.1` codebase I can confirm we no longer have this restriction (and everything goes into a mongo collection anyway).  Closing this out as we'll really not be actively developing `1.0` outside of any major backports for folks still running it.
