### ISSUE TITLE
[RFE] Check for Foreman flag on broken host before scheduling

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#190]
**Is your feature request related to a problem? Please describe.**
As a user I would like to prevent Quads from scheduling host that have the broken flag set to true on Foreman.

**Describe the solution you'd like**
Before scheduling a host, check with Foreman if this host is marked as broken, display an error message if so.

**Describe alternatives you've considered**
Query Foreman for all broken hosts before scheduling, verify if host belongs to broken hosts and if so display an error message stating the reason for not being able to schedule that particular host.

**Comment by sadsfae** [comment]
This needs review (and probably our CI is busted / needs attention):

@grafuls review:

https://review.gerrithub.io/c/redhat-performance/quads/+/425750
