### ISSUE TITLE
New clouds without history don't render first month correctly in visuals

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#202]
There's an issue with visuals being created for new clouds that do not have a cloud history, in that the first month generated will be blank in the visuals because there is no history that has existed yet.

https://github.com/redhat-performance/quads/blob/master/bin/simple-table-generator.py#L122

We probably need to set the time epoch for the cloud to `0000` if there is no cloud history defined.

**Comment by sadsfae** [comment]
@grafuls @kambiz-aghaiepour whatever is employed for a fix here we will need to backport into `1.1`

**Comment by grafuls** [comment]
This has been resolved with the move to mongo.
