### ISSUE TITLE
Add Public SSH Keys to New Cloud Assignments Automatically

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#207]
This is an RFE to add users public SSH keys to new assignments automatically via QUADS during `bin/move-and-rebuild-host.sh`.  This would require an open git repository where users can store their intended public SSH keys named `username.pub`.  If either the `--cloud-owner` or any of the `--cc-users` for a particular environment match any of the keys in place then it will copy them onto all their hosts.

Right now we have a playbook that tenants can utilize to copy keys but this will make things more seamless out of the box (and avoid hard coding uneccesary/irrelevant keys in Foreman)

https://github.com/redhat-performance/ops-tools/tree/master/ansible/copy-ssh-keys

**Comment by grafuls** [comment]
We could use something like this:
https://gist.github.com/grafuls/f279239c8bfe478020c266febeb37c79

**Comment by sadsfae** [comment]
Updated here: the bits @grafuls put together for this tool here should be a good entry-point into having quads do this for us:

https://github.com/redhat-performance/ops-tools/blob/master/misc-tools/paramiko-copy-ssh-key.py

This can be done with `1.0` branch also but we'll need to add `python-paramiko.noarch` for EL7/Fedora for the RPM spec so that's satisfied.

**Comment by sadsfae** [comment]
Closing this issue, it's over five years old and we've just been pointing tenants to a lightweight SSH key copy playbook:  https://github.com/sadsfae/ansible-sshkeys

Also wrangling SSH keys from users is similar to herding cats and might seem like a good idea but requires more pre-assignment coordination than it's worth unless we capture the keys on our internal request submission codebase/landing page.
