### ISSUE TITLE
--cc-users returns exception on Alpha 1.1 codebase

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#208]
When using the `quads --cc-users` defining a new cloud we get the following error:

```
[root@host-04 ~]# quads --define-cloud cloud05 --description "so what" --cloud-owner epresley --cc-users "jbrown evanhalen" --qinq 1 --cloud-ticket 12345
["Error: ValidationError (Cloud:None) (Only lists and tuples may be used in a list field: ['ccuser'])"]
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/446913

**Comment by sadsfae** [comment]
This should be resolved in https://github.com/redhat-performance/quads/commit/e2d7b0111b70d49abcc8f65f86b7b6c0517db816
