### ISSUE TITLE
Database validated/notified/released fields don't exist on CloudHistory for new Clouds

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#213]
We seem to have a bit of a chicken-and-egg problem with the `notified` `released` and `validated` flags for the `CloudHistory` document.  They don't exist at time a new cloud is created so they issue a warning:

```
 'Error: The fields "{\'validated\', \'notified\', \'released\'}" do not exist on the document "CloudHistory"']
```

(tested against latest RPM build against master 2019-03-09 https://github.com/redhat-performance/quads/commit/56b0c963b3db20770f63f0e4e63289b19d9e371c )
```
[root@host-04 ~]# quads-cli --define-cloud cloud01 --description "resource pool"
['Created cloud cloud01', 'Error: The fields "{\'validated\', \'notified\', \'released\'}" do not exist on the document "CloudHistory"']
[root@host-04 ~]# quads-cli --define-cloud cloud04 --description "fun pool"
['Created cloud cloud04', 'Error: The fields "{\'validated\', \'notified\', \'released\'}" do not exist on the document "CloudHistory"']
```

However this is just a warning, it still seems to work:

```
[root@host-04 ~]# quads-cli --ls-clouds
cloud01
cloud04

[root@host-04 ~]# quads-cli  --full-summary
cloud01: 0 (resource pool)
cloud04: 0 (fun pool)
```

Subsequent updates of a cloud also produce warnings:

```
[root@host-04 ~]# quads-cli --define-cloud cloud01 --force --description "primary resource pool"
['Updated cloud cloud01', 'Error: The fields "{\'validated\', \'notified\', \'released\'}" do not exist on the document "CloudHistory"'
```

**Comment by grafuls** [comment]
This is due to the fields being added to Cloud but not the cloud history since they are not relevant for it.
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/447544

**Comment by sadsfae** [comment]
This is confirmed fixed.
