### ISSUE TITLE
stdout output from quads-cli is on drugs

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#218]
In the latest `master` codebase as of https://github.com/redhat-performance/quads/commit/45829e260cbe5a6d7b2dd4cec4f3465870758710 when piping the stdout output of `bin/quads-cli` the output is not valid utf-8 text but identifies as some weird dos format with ASCII text and CRLF line terminators.  This might be due to the logging library.

As a result you cannot parse and re-use stdout to feed back into quads, it needs to be copied or manipulated before consuming it.

e.g.

```
(root@quads) - (10:27) - (~)
-=>> quads --ls-hosts > /tmp/testing.txt

(root@quads) - (10:49) - (~)
-=>> file !$
file /tmp/testing.txt
/tmp/testing.txt: ASCII text, with CRLF line terminators
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/449582
