### ISSUE TITLE
quads-cli --cloud-only --date doesn't render past or futures

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#222]
As of latest master code https://github.com/redhat-performance/quads/commit/4e8a87cb5fd038c01af43efdcccac415b07529e5 the following doesn't work but should:

```
quads-cli --cloud-only cloud03 --date "2019-03-21 14:31"
```

The converse should happen for looking up future assignments too.

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/449452
