### ISSUE TITLE
cloud01 is being omitted in --summary output

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#229]
When there are hosts in cloud01 it would be good to see the output of quads-cli --summary include cloud01.  It appears to be omitted currently.

**Comment by grafuls** [comment]
The issue here is that now we rely on current_schedule to return summary. Since we do not create schedules for cloud01, the host count for this will always be 0.
We need to consider an additional handler for cloud01 on get_summary.

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/451051
