### ISSUE TITLE
Bring back per-assignment counts 

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#230]
in QUADS `1.0` we used to have per-assignment machine counts next to the assignment summary, let's bring those cats back in.

![Screenshot_2019-04-12_09-36-39](https://user-images.githubusercontent.com/3940978/56041422-b1760700-5d06-11e9-9168-8e7909480154.png)

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/451051
