### ISSUE TITLE
Assignments can be released but not validated

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#233]
Assignments can be released but still not be validated.

```
> use quads;
switched to db quads
> db.cloud.find({name: "cloud07"})
{ "_id" : ObjectId("5c82b36a0f767d000692ad01"), "name" : "cloud07", "description" : "Storage Workload LTA", "owner" : "jharriga", "ticket" : "488919", "qinq" : true, "wipe" : true, "ccuser" : [ "bengland", "dfuller", "frival", "rsussman" ], "released" : true, "validated" : false, "notified" : false }
```

Namely:

```
"released" : true, "validated" : false,
```

On the automated wiki we see it's released.

![Screenshot_2019-04-15_13-02-50](https://user-images.githubusercontent.com/3940978/56151347-091ea780-5f7f-11e9-8d97-2e8bd008a8fe.png)

We should be doing the following:

- Released cannot be true if validated is not true as it pertains to QUADS workflow

**Comment by grafuls** [comment]
This might be a case of poor wording.
Released=True means move and rebuild has been successful which is the step before validation.
Do we want to change this to "provisioned"?
Additionally I'll try to address the wiki to not show the cloud as ready before validation.

**Comment by sadsfae** [comment]
> This might be a case of poor wording.
> Released=True means move and rebuild has been successful which is the step before validation.
> Do we want to change this to "provisioned" or something alike?
> Additionally I'll try to address the wiki to not show the cloud as ready before validation.

Aye, that's probably best I think because `Released=True` seems more like the entire assignment has passed all validation steps and is available.

**Comment by sadsfae** [comment]
This should be resolved in https://review.gerrithub.io/c/redhat-performance/quads/+/451493/18
