### ISSUE TITLE
Mongoengine seems to cache --move-hosts actions until quads-server bounced

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#234]
We still have a strange behavior in that after entering scheduling actions `--move-hosts` show `nothing to do` but when `quads-server` is bounced it picks up the results.

This we thought was the fix but it still occurs, we should probably revert this until we can figure out where this is getting cached:

https://github.com/redhat-performance/quads/commit/efc0fa98e1213a9ede1c581dd14fe6dbb6e4c4d1

For now, a mitigation for this is to simply issue `systemctl restart quads-server` after a new future schedule is entered.

**Comment by grafuls** [comment]
Possible solution second attempt:
https://review.gerrithub.io/c/redhat-performance/quads/+/454253

**Comment by sadsfae** [comment]
Not really sure where/how to debug this, it only appears to happen when the `--move-hosts` functionality is called.

https://github.com/redhat-performance/quads/blob/master/bin/quads-cli#L302

When other data is added/updated into MongoDB via Mongoengine ORM it can be queried immediately and reports back accurately.

We run this functionality out of cron currently, so every 5minutes if systems were set to either be moved somewhere else (or reclaimed) it'll pick up on it.

```
*/5 * * * * flock -n /tmp/moveandrebuild.lock -c "/opt/quads/bin/quads-cli --move-hosts" 1>>/var/log/move-and-rebuild.log 2>&1
```

@radez have you ever seen this kind of behavior?

**Comment by grafuls** [comment]
I think we have a winner:
https://review.gerrithub.io/c/redhat-performance/quads/+/454588
