### ISSUE TITLE
Re-implement quads-cli --date

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#235]
In `1.0` we had the facility of `quads-cli --date "YYYY-MM-DD HH:MM" which yielded the following output based on future schedules:

```
quads-cli --date "2017-03-06"

cloud01:
  - b09-h01-r620.rdu.openstack.engineering.example.com
  - b09-h02-r620.rdu.openstack.engineering.example.com
  - b09-h03-r620.rdu.openstack.engineering.example.com
  - b09-h05-r620.rdu.openstack.engineering.example.com
  - b09-h06-r620.rdu.openstack.engineering.example.com
```

We should implement this for `1.1`.

**Comment by sadsfae** [comment]
It looks like the API endpoints are missing for this:

https://github.com/redhat-performance/quads/blob/master/bin/quads-cli#L455

**Comment by grafuls** [comment]
This has been addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/456595

Note the functionality for this is under --ls-schedule:
```
quads-cli --ls-schedule --date "2017-03-06"
```
