### ISSUE TITLE
7,5,3,1 day messages using wrong template

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#242]
7,5,3,1 day **expiration** messages should be using `/quads/quads/templates/message` instead of `/quads/quads/templates/future_message` which is set aside (and sent only once) for scenarios that machine are **added** to an existing assignments only.

`/quads/quads/templates/message` should get sent for 7,5,3,1 day expiration notifications.

`/quads/quads/templates/future_message` should be sent for once, for either a 7,5,3,1 day period (depending on which fits closest to when machines were added to an assignment after it went out) to notify the owner that new machines will be added to their cloud from somewhere else.

**Comment by grafuls** [comment]
Attempt to address this here:
https://review.gerrithub.io/c/redhat-performance/quads/+/454455
