### ISSUE TITLE
quads-cli violates the laws of physics

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#246]
`quads-cli` thinks that a physical host can be in two places at the same time.

Currently `quads-cli` is reporting that a host is both in the correct cloud but also still exists in cloud01.  

```
quads-cli --cloud-only cloud01 | grep f24-h01-000-r630
f24-h01-000-r630.rdu2.example.com
```

However it really is in cloud15

```
quads-cli --host f24-h01-000-r630.example.com
cloud15
```

Full schedule we can see it's in the right place, however because `quads-cli` reports it in both places at the same time corresponding wiki generation as well as any data or reporting using `quads-cli` will be incorrect

```
quads --ls-schedule --host f24-h01-000-r630.rdu2.example.com
Default cloud: cloud01
Current cloud: cloud15
Current schedule: 2
1| start=2019-04-30 15:15:00, end=2019-05-05 22:00:00, cloud=cloud10
2| start=2019-05-19 22:00:00, end=2019-06-02 22:00:00, cloud=cloud15
```

**Comment by grafuls** [comment]
This is related to:
https://github.com/redhat-performance/quads/issues/245
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/455278
