### ISSUE TITLE
default cloud for a host should be static unless purposely redefined

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#247]
We seem to associate `default cloud` with whatever cloud a host is in currently, this should never change from the value when defining a host for the first time via `quads-cli --define-host --default-cloud`

**Comment by sadsfae** [comment]
This will require some architectural overhaul with a new field in mongo, there are also some logic assumptions that things will move back to cloud01 regardless of what is set via a hosts ``--default-cloud`

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/462438
