### ISSUE TITLE
vlan wiki cleanup needs to occur for previously used, now empty environments

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#248]
We need to employ similar logic like https://github.com/redhat-performance/quads/blob/1.0/bin/find-free-cloud.py in the way we generate/display vlans on the QUADS wiki.

**Logic**
When regenerating the QUADS VLAN wiki page we should check against cloud environments that have vlan id's associated with them and not display them on the wiki.

Because the actual backend VLAN configs will be removed when that cloud is recycled (where cleanup actually happens) we don't need to worry about that but we do want updated visualizations updated so we know what's really available to re-use.

**Comment by grafuls** [comment]
This has been addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/455796/4/bin/quads-cli#346
