### ISSUE TITLE
quads-cli incorrectly showing default-cloud for hosts in assignment

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#249]
Somewhat related to https://github.com/redhat-performance/quads/issues/247 this is a minor bug in `quads-cli` that displays the incorrect output in quads cli.

**Comment by grafuls** [comment]
Addressed here: https://review.gerrithub.io/c/redhat-performance/quads/+/462438

**Comment by sadsfae** [comment]
Closing, addressed in https://github.com/redhat-performance/quads/commit/54d788255f0a51d62a74246514f34c0bcbe59b1a
