### ISSUE TITLE
Cloud Wipe setting needs to reset on --define --force

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#251]
It appears that the `wipe: 0/1` setting of `quads-cli --define-cloud` does not reset when an environment is redefined for future use.

The expected behavior here is that this value is reset back to the default.

Most people will want to wipe before proceeding with deploying new infrastructure.

**Comment by grafuls** [comment]
If we are having a default of wipe=True then why not refactor this to a cli boolean flag for --no-wipe.
When passed wipe=False when not passed wipe=True.
(?)

**Comment by grafuls** [comment]
Addressed here as per my last comment:
https://review.gerrithub.io/c/redhat-performance/quads/+/455796
