### ISSUE TITLE
RFE:  --mod-cloud argparse for modifying some cloud attributes

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#252]
This is an RFE for something akin to a `quads-cli --mod-cloud` argparse that allows for modification of the following metadata for an active cloud environment where it's not required to pass all attributes into `--define-cloud` to achieve the same thing.

**Values we should be able to change with `--mod-cloud`**

* `cc-users`
* `wipe`
* `description`

**Values we should be able to change with `--mod-cloud` that could activate changes:**

* `qinq` (running `/quads/tools/verify_switchconf.py` would then change vlan design)
* `vlan` (running `/quads/tools/juniper_convert_port_public.py` would then change public vlan)

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/505089
