### ISSUE TITLE
find-free-cloud and ensuring --define is disallowed on environments with future hosts

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#253]
This should track any changes that need to be made to ensure the following behavior

* We should not be able to run `quads-cli --define-cloud --force` against any cloud that will contain future hosts in it.

* We should have a facility similar to https://github.com/redhat-performance/quads/blob/1.0/bin/find-free-cloud.py as an argparse option in `quads-cli` to report on cloud environments that do not have future hosts scheduled in them.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/455837
