### ISSUE TITLE
Badfish obsessing over certain hosts and validate_env not being run

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#255]
This is to log bug(s) discovered during our most recent large-scale deployment of 309 hosts via cloud12 on `2019-05-28`.

**Issues**

* badfish libraries can get obsessed with hosts that return a 400 error or otherwise some response it does not understand from redfish API.

* validate_env never gets parsed because provisioned flag never gets set so things just endlessly chomp chomp

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/456242
