### ISSUE TITLE
Error when calculating vlan in move_and_rebuild_hosts.py

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#258]
There may be a bug in the way old vlan calculation is done in some situations:

https://github.com/redhat-performance/quads/blob/master/quads/tools/move_and_rebuild_hosts.py#L67

Not positive this is a bug, putting here to keep an eye on it.

```
Move command failed for host: f04-h15-000-r620.rdu2.example.com
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 359, in main
    next_provision = move_and_rebuild(host, current, new, cloud.wipe)
  File "/opt/quads/quads/tools/move_and_rebuild_hosts.py", line 67, in move_and_rebuild
    old_vlan = old_vlan_out[0].split(";")[0].split()[1][7:]
IndexError: list index out of range
```

**Comment by grafuls** [comment]
Should be resolved here:
https://review.gerrithub.io/c/redhat-performance/quads/+/457490
