### ISSUE TITLE
quads-cli --cloud-only cloud01 requires --date

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#259]
`quads-cli --cloud-only cloud01` should return all systems in cloud01 but instead we get:

```
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 520, in <module>
    main(args)
  File "/opt/quads/bin/quads-cli", line 407, in main
    if _kwargs["date"] and _args.cloudonly == "cloud01":
KeyError: 'date'
```

This works fine for other environments however.

In order to get the same CLI functionality you need to pass `--date`

e.g.

```
quads-cli --cloud-only cloud01 --date "2019-06-05 14:54"
f03-h30-000-r720xd.rdu2.example.com
f04-h01-000-r630.rdu2.example.com
f04-h02-000-r630.rdu2.example.com
f04-h03-000-r630.rdu2.example.com
f04-h13-000-r630.rdu2.example.com
f05-h31-000-1029p.rdu2.example.com
f06-h29-000-1029p.rdu2.example.com
f24-h21-000-r630.rdu2.example.com
f24-h22-000-r630.rdu2.example.com
f24-h23-000-r630.rdu2.example.com
f24-h24-000-r630.rdu2.example.com
f25-h33-000-r630.rdu2.example.com
f23-h21-000-6048r.rdu2.example.com
```

Probably, we want to assert `datetime.now()` if `_kwargs["date"]` is not passed.

https://github.com/redhat-performance/quads/blob/master/bin/quads-cli#L407

**Comment by sadsfae** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/457011

**Comment by grafuls** [comment]
@sadsfae just realized you were already working on it but here is my take:
https://review.gerrithub.io/c/redhat-performance/quads/+/457454
