### ISSUE TITLE
validate_env should base network check on mongo-defined interfaces

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#262]
https://github.com/redhat-performance/quads/blob/master/quads/tools/validate_env.py should be basing it's network fping test for backend, internal vlan interfaces on the number of interfaces defined in mongodb for the host collection.

This will catch issues where some system types may have less than 4 x internal interfaces.

We might create a list of mongodb host interfaces then count the number of items in the list to know how many fping interfaces are in play.

**Comment by kambiz-aghaiepour** [comment]
I didn't think it was assumed the hosts have 4 interfaces.  I thought the interface list was pulled out of mongo per host, and the hosts with less than 4 interfaces would get pinged only on the IPs that they have (e.g. only 3 IPs on 5039ms hosts)

**Comment by sadsfae** [comment]
> I didn't think it was assumed the hosts have 4 interfaces. I thought the interface list was pulled out of mongo per host, and the hosts with less than 4 interfaces would get pinged only on the IPs that they have (e.g. only 3 IPs on 5039ms hosts)

That's how it used to work, I believe we need to address this again.

**Comment by grafuls** [comment]
That is how it is currently working:
https://github.com/redhat-performance/quads/blob/master/quads/tools/validate_env.py#L121

I believe this issue to be on the switch side, probably cables issue.
We rerun validations against 3 other 5039ms and validation was successful.
