### ISSUE TITLE
RFE: Create free-form metadata fields for hosts collection

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#263]
We will need the ability to store free-form string/text data about hosts that can be queried with quads.  This can be useful in situations where you might have differences among system types of the same model or in general for querying more data about hosts.

For example, we have SuperMicro 1029u systems that differ via

- 4 x 2TB NVMe versus 1 x NVME
- provisioning interface on 10GbE

**Proposal Suggestion**

Things will get muddied up quick with only a general metadata field, so we should probably organize it based on component and be consistent with the data.

| Collection | Component | Example Data |
|----------------|------------------|----------------------|
| host.meta.model | SSR-1029U-TRTP | SuperMicro Model Type |
| host.meta.disk.type | nvme.2tb,ssd.500g | Host has 2TB NVMe and 500G SSD |
| host.meta.disk.count | 36.sata | Host has 36 x SATA disks |
| host.meta.pdu | None | Host does not have independent PDU |
| host.meta.pdu | pdu1:port1,port2 | Example PDU sockets connected for controlling via QUADS |
| host.meta.nic.nic1.maintenance | True | nic1 of host is in maintenance mode |

NIC info should be part of `--ls-interfaces` and the model we already use for interfaces

**Implementation**

In additional to new data fields within the host collection per host, we should also make this queryable via `quads-cli` perhaps with a `--search` argparse parameter.

Additionally it might be nice to just return the data if you know the full host collection object string.

e.g.

`quads-cli --info --host host01.example.com disk.count`

**Differences**

We might elect to highlight or change the text in wiki and heat map for a host (light green vs. normal?) **only** when a distinguishable characteristic is notable among the same server generation type.

e.g.

* One type of SuperMicro 1029U has 4 x 3TB NVMe
* One type of SuperMicro 1029U has 2 x 3TB NVMe

**Result**

The *higher* or *improved* server type text is green on wiki and heat map visualization, making it stand out from the others.

Otherwise, the additional fields should be searchable via `quads-cli` for data and informational purposes if they don't qualify for the host to stand out.

**Comment by abondvt89** [comment]
We need to prioritize this now.  We are going to have more systems within a machine type that have different capabilities and hardware options.  (nics, nic types, # drives, drive type, etc)

**Comment by sadsfae** [comment]
Let's also better understand how we will consume this.

e.g. here are a few:

`--ls-available` (and how would that look)

`--ls-hosts`

Are there visual distinctions we want to have?  Perhaps a small indicator like `*` on the wiki / visuals?

**Comment by sadsfae** [comment]
We should also support conditional output of `and` and `or` for search.

**Comment by bengland2** [comment]
It's not clear to me where you are storing this data or how people can get at it without access to the QUADS UI.   For example, would this data be available in 

http://quads.rdu2.scalelab.redhat.com/cloud/cloudNN_ocpinventory.json

so that install playbooks could make use of it?

**Comment by smalleni** [comment]
@bengland2 once the data is in the quads DB somehow, it should be straightforward to expose it in the file. That's what I did in that file. @grafuls the maker of the server be a part of the metadata (supermicro/dell)?

**Comment by QuantumPosix** [comment]
I think its very important to capture a few other fields, RAM total, GPU's, processor type and the likes.

**Comment by sadsfae** [comment]
You can see the WIP patchset here:

https://review.gerrithub.io/c/redhat-performance/quads/+/494554

The first pass is not complete, just a work-in-progress.

> @grafuls is the manufacturer of the server going to be a part of the metadata (supermicro/dell)?

Yes.  Likely the `host_type` field will be purposed for this - right now it's just a placeholder of `vendor`.

> It's not clear to me where you are storing this data or how people can get at it without access to the QUADS UI. For example, > would this data be available in

> http://quads.rdu2.example.com/cloud/cloudNN_ocpinventory.json

> so that install playbooks could make use of it?

This data is not for consumption outside of QUADS, it's going to enable and feed other things we are doing.  Eventually we will open up the QUADS API for things like this or if certain datasets are useful we may generate pages with said data.

This will not become part of the ocp/osp inventory.

You can see the kind of data we'll be collecting to do an initial seed of existing hosts as part of the WIP patchset (which is by no means complete yet or exhaustive yet).

https://review.gerrithub.io/c/redhat-performance/quads/+/494554/4/conf/hosts.yml

**Comment by grafuls** [comment]
> You can see the WIP patchset here:
> 
> https://review.gerrithub.io/c/redhat-performance/quads/+/494554

Closing this issue as first patch has already been merged and used in production.

> 
> The first pass is not complete, just a work-in-progress.
> 
> > @grafuls is the manufacturer of the server going to be a part of the metadata (supermicro/dell)?
> 
> Yes. Likely the `host_type` field will be purposed for this - right now it's just a placeholder of `vendor`.
> 
> > It's not clear to me where you are storing this data or how people can get at it without access to the QUADS UI. For example, > would this data be available in
> 
> > http://quads.rdu2.example.com/cloud/cloudNN_ocpinventory.json
> 
> > so that install playbooks could make use of it?
> 
> This data is not for consumption outside of QUADS yet, it's needed to enable and feed other things we are doing on our roadmap. Eventually we will open up the QUADS API for things like this or if certain datasets are useful we may generate pages with said data if it's useful for folks but that's not in scope of the first implementation of this RFE.
> 
> There will be some additional, useful representations of system attributes from this that will be inherent with this RFE however but it is mostly a foundational change that allows other roadmap features and enhancements down the road.
> 
> Here's some of the things we're doing with it:
> 
> * Tackle the problem of hardware drift and differing HW configurations among subsets of systems of the exact same type.
> * Provide more accurate queries and eventually "recommendations" of groups of systems to schedule based on specific HW capabilities.
> * Provide more accurate reporting and usage metrics
> * Provide more in-depth hardware breakdowns and asset attributes of systems (when we move to Flask and phase 1 of the UI)
> * Pave way for subsets of self-scheduling when we move to Phase 2 of our UI
> * Generate and maintain accurate, in-depth system info for all systems in the R&D labs
> * In general, allow us to replace the wiki, assignments page, requests page and extensions page to be served directly off QUADS and pull in more dynamically created, refreshed content and features than what's in place now.
> 
> This is not planned to become part of the ocp/osp inventory in this scope of this RFE. _We need this to drive other longer-planned RFE and features and solve some immediate problems we have right now._
> 
> @bengland2 If you want a very easy, 5-second way to gather all the hardware info about your systems in an assignment right now you should look at using ansible-cmdb https://github.com/fboender/ansible-cmdb and running this once when you get an allocation handed out. You run it once, it takes 5-10 seconds or so depending on amount of systems and you've got all the info ansible facts can generate for you. It will generate HTML, CSS, SQL, CSV, JSON and other outputs.
> 
> Any implementation of a user-facing "data store" about systems hardware will be another RFE that leverages this functionality unless we simply re-implement the ansible-cmdb like functionality that we have before which is also planned - we'll have to see which approach is most advantageous.
> 
> You can see the kind of data we'll be collecting to do an initial seed of existing hosts as part of the WIP patchset (which is by no means complete yet or exhaustive yet). Some of this information may be limited to what the Redfish API reports however.
> 
> https://review.gerrithub.io/c/redhat-performance/quads/+/494554/4/conf/hosts.yml
> 
> If there's some stuff we can expose that is useful to automation within the lab based on this data or otherwise we're happy to do it. We'd need some help to show us what kind of data and format that might entail.
