### ISSUE TITLE
--ls-available should not return broken hosts

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#264]
**Describe the bug**
When running --ls-available we are not discriminating hosts marked as broken from Foreman.
We should not considering broken hosts as available since this will be then rejected when adding schedule to Quads.

**To Reproduce**
1. Add broken=true host parameter on foreman to an available host
2. run `quads --ls-available`
3. Scroll down to find broken host.

**Expected behavior**
Broken hosts should not be listed.

**Comment by sadsfae** [comment]
Aye, this would be good enhancement.
