### ISSUE TITLE
RFE: Implement a duration capability into schedule

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#267]
Most reservations start and end at the same time and as long as a start date and duration is provided will populate the end date accordingly. Give the option to put in a duration into the schedule which automatically calculates the end date of a reservation.

**Comment by grafuls** [comment]
YAS! :raised_hands:

**Comment by sadsfae** [comment]
This is a solid improvement and would keep us from having to run this logic in shell.

e.g.

```
quads-cli --extend-schedule --cloud cloud10 --schedule-end "2019-08-08 22:00"
```

Replaces this:

```
modcloud=cloud05
for h in $(quads-cli --cloud-only $modcloud); do quads-cli --mod-schedule $(quads-cli --ls-schedule --host $h | grep $modcloud | grep "end=2019-02-09" | tail -1 | awk -F\| '{ print $1 }') --host $h --schedule-end "2019-03-06 22:00" ; done
```

**Comment by grafuls** [comment]
Would be nice to have something like:
`quads-cli --extend-schedule --cloud cloud10 --weeks 2`

**Comment by QuantumPosix** [comment]
I agree with @grafuls if we use a date that uses combination of weeks / days to extend to give more granular control as we know what time reservations end .

**Comment by sadsfae** [comment]
In addition to this RFE we should add the ability to set `--extension-interval $weekvalue` to the QUADS cloud document and a setting in `quads.yml` for `default_extension_interval` to set a default.

1) If `--extension-interval` is set it overrides `default_extension_interval` in `quads.yml`
2) allows for running `quads-cli --extend-schedule --cloud cloud10` and not specifying an interval if one isn't given.

**Comment by kambiz-aghaiepour** [comment]
This may address what Ashish had issues with.  Perhaps based on manager input, each cloud can also have a default length (DL) for extensions.  Given that extensions are becoming a necessary evil (considering allocations can be predictive but unforeseen issues or bugs can also create delays necessitating extension requests).  How this might work is:

scenario 1:
define a cloud with a 1 week extension default:
`quads-cli --force --define-cloud cloud02 --extenstion-dl 1 [... other required options ...]`

define a cloud with a 2 week extension defult:
`quads-cli --force --define-cloud cloud02 --extenstion-dl 2 [... other required options ...]`

and then when you do:

`quads-cli --extend-schedule --cloud cloud02`

it will use the DL for cloud02.  A general setting can also be set in quads.yml as outlined above.

**Comment by kambiz-aghaiepour** [comment]
interval might be clearer than DL.

**Comment by QuantumPosix** [comment]
Why cant we just use --extend and add a config parameter in the cloud as a
default  or an modified extension setting

~ Thanks,

Chris
978.392.1043

**Comment by sadsfae** [comment]
> Why cant we just use --extend and add a config parameter in the cloud as a default or an modified extension setting ~ Thanks, Chris 978.392.1043


I think that's what we're saying here.

https://github.com/redhat-performance/quads/issues/267#issuecomment-601787188

**Comment by grafuls** [comment]
> Would be nice to have something like:
> `quads-cli --extend-schedule --cloud cloud10 --weeks 2`

also would be nice to have an additional option like `--check` for not doing the actual extension but just to verify that the already assigned hosts can be extended.
