### ISSUE TITLE
When changing the overcloud parameter from false to true, the host is not included in the instackenv.json

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#269]
When the first host in the assignment has its foreman param changed from overcloud: false to overcloud: true, it is still not included in the instackenv.json.

**Comment by kambiz-aghaiepour** [comment]
https://github.com/redhat-performance/quads/blob/ff01e5e0196338c4a4df47088d1fc0a51eeae27c/quads/tools/make_instackenv_json.py#L43

it looks like we only consider the host list for all hosts after the first one, such that the overcloud = true / false has no effect on the first host.  We should allow for an easy way to add the first host into the generated instackenv.json
