### ISSUE TITLE
RFE: Replace paramiko with libssh

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#270]
`python3-paramiko` is going to be removed in EL8 in lieu of `libssh` and in other places as well (like Ansible).  Overall, libssh proves some very tangible performance benefits over paramiko along with no real dependencies as it uses the system C libraries.

https://parallel-ssh.org/post/ssh2-python/

We should look instead to package and utilize `python3-ssh2-python` which provides the Python wrapper integration into `libssh`

https://github.com/ParallelSSH/ssh2-python

**Comment by grafuls** [comment]
Leaving this on hold for the time being. Not able to execute more than 1 command in 1 session and not much support for this python library.

**Comment by sadsfae** [comment]
Closing this issue, `libssh` has still not yielded the amount of adoption and community usage that we'd like four years later.
