### ISSUE TITLE
Build in automated public vlan culling

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#272]
When systems that are utilizing the automated public vlan allocation for assignments (`quads-cli --define-cloud cloud0X --vlan $vlanid`) we currently do not have a culling mechanism to remove unused vlan associations to cloud assignments when they expire.

We can utilize the same logic used for `provisioned` flag at the cloud metadata level for this.

**Comment by grafuls** [comment]
This is already in place:
https://github.com/redhat-performance/quads/blob/master/bin/quads-cli#L374
