### ISSUE TITLE
ssh_helper / validation needs to omit the 4th interface for public VLAN clouds

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#275]
With the automated public vlan option for assignments, the 4th interface will be tagged natively with a publically routed vlan if the `--vlan` option is defined.

We need to reflect this with the fping tests done in https://github.com/redhat-performance/quads/blob/master/quads/tools/validate_env.py#L112

**Comment by kambiz-aghaiepour** [comment]
currently we are testing:

INTERFACES = {
    "em1": ["172.16", "172.20"],
    "em2": ["172.17", "172.21"],
    "em3": ["172.18", "172.22"],
    "em4": ["172.19", "172.23"],
}

these arrays are the UNTAGGED and TAGGED subinterfaces.  For example, if the host has 4 interfaces, then the UNTAGGED interface IP address is  : 172.19.$x.$y (where $x is the 3rd octet of the public IP address of the host, and $y is the 4th octet of the public IP address of the host), and the TAGGED interface IP address is: 172.23.$x.$y

Now for environments where we use a public VLAN, we need to omit the TAGGED subinterface IP address from the ping list, but we can still include the UNTAGGED interface IP address.  So for example we would want to do the following for an environment with hosts where all hosts have 4 interfaces:

INTERFACES = {
    "em1": ["172.16", "172.20"],
    "em2": ["172.17", "172.21"],
    "em3": ["172.18", "172.22"],
    "em4": ["172.19"],
}

**Comment by kambiz-aghaiepour** [comment]
Of course the logic will need to be clever so that for hosts that only have 3 interfaces (for example the 5039ms hosts), we would test:

INTERFACES = {
"em1": ["172.16", "172.20"],
"em2": ["172.17", "172.21"],
"em3": ["172.18""],
}

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/462511
