### ISSUE TITLE
Removing a host with an active schedule causes traceback

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#276]
When removing a host via `--rm-host` no check is done if the host has active schedules, which leaves some orphaned data in the database collection.

```
  File "/usr/lib/python3.7/site-packages/mongoengine/fields.py", line 1076, in __get__
    raise DoesNotExist('Trying to dereference unknown document %s' % value)
mongoengine.errors.DoesNotExist: Trying to dereference unknown document DBRef('host', ObjectId('5d28c93291370657990eaf06'))
```

**Comment by grafuls** [comment]
Addressed here:
https://review.gerrithub.io/c/redhat-performance/quads/+/462581/

**Comment by sadsfae** [comment]
https://github.com/redhat-performance/quads/commit/48faaca91b4889dfc6c052aa0285620a200dd949
