### ISSUE TITLE
[RFE] Update to include Server Utilization on the Visualizations Page

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#287]
Have a way of listing monthly server utilization % at the top of the visualizations page

By using the grey square calculations based off the current day get an accurate represented used % that is displayed and captured for that month

currently run the following on the files to get this information

```
grep "domain.com" 2019-09.html | wc -l
grep "#bec1d4" 2019-09.html | wc -l {unused days}

{# of systems} * {total days} = {operating days}
(100-({unused}/{operating}*100))
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/471508
