### ISSUE TITLE
Foreman RBAC fail after two machines on some assignments

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#291]
* QUADS version (`rpm -qa | grep quads` and/or `quads-cli --version`):

`quads-dev-1.1.0-20191017.noarch`

* Python version:
`3.7.4`

* Operating System:
Fedora 29

**Describe the bug**
Foreman RBAC changes don't always work, they seem to include two machines then bomb out.

Running `/opt/quads/quads/tools/foreman_heal.py` fixes things.

There seems to be a pattern here, as a previous assignment that went also only had two systems processed (out of 16) with the correct RBAC roles.

Possibly this is related to the Foreman bug and our semaphore workaround?

https://projects.theforeman.org/issues/27953

One potential workaround is to just call `/opt/quads/quads/tools/foreman_heal.py` right before assignments go out for good measure, though that really doesn't fix the problem.

**Comment by sadsfae** [comment]
This will be solved when the following patchset is implemented:

https://review.gerrithub.io/c/redhat-performance/quads/+/473208

**Comment by grafuls** [comment]
> This will be solved when the following patchset is implemented:
> 
> https://review.gerrithub.io/c/redhat-performance/quads/+/473208

Patchset merged
