### ISSUE TITLE
Adding more hosts to an existing cloud in the future triggers re-validation

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#304]
* QUADS version `quads-1.1.2-20191216.noarch` (same as `quads-dev` or master branch)
* Python version: `Python 3.7.4`
* Operating System: `Fedora 29`

**Describe the bug**
Adding additional hosts to an existing assignment that will join well into the future seems to toggle the cloud validation back to `validating` on the wiki.

What seems to be happening is there isn't a check that if hosts are added to join later (beyond current datetime = now) somehow the validate flag gets toggled at the cloud level.

![Screenshot_2019-12-19_18-38-28](https://user-images.githubusercontent.com/3940978/71199861-ca1fbf00-228e-11ea-8003-b37ea6d7d8f0.png)

The example above, 300 x systems were scheduled to be added to `cloud12` on `2020-01-05 22:00` however right now, prior to that, the cloud reverted to `Validating`

I have not looked into the code base deeper but there's been some recent feature commits that address validations to systems added to already existing environments and may be related:

https://github.com/redhat-performance/quads/commit/cc5737d303c78c3e58580b7bd009b0c10d252b46

**Comment by kambiz-aghaiepour** [comment]
Looking at:

https://review.gerrithub.io/c/redhat-performance/quads/+/477967/2/quads/api_v2.py

we actually don't really consider the start time when we mark the cloud as validation=False.  We would have to have a way of knowing that a future schedule is about to kick in (which means a process loop that constantly looks at the "about to kick in" schedules) and only toggle the cloud level Validation attribute to False at a designated time.  I'm not sure if this is worthwhile.  This is worthy of discussion.
