### ISSUE TITLE
Have user pick undercloud when generating instackenv.json

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#31]
Currently, QUADS assumes that the first host in the allocation is the undercloud and generates instackenv.json based on that. It becomes cumbersome to manually edit the isntackenv.json if using some other host as undercloud. It would be great if QUADs can support any host as the undercloud.

**Comment by smalleni** [comment]
@wilkins11 faced this.

**Comment by sadsfae** [comment]
We have a way to do this on the QUADS side and can override the choosing of the first node, we just need to discuss and finalize an easier way to extend this to equipment that QUADS provides to Engineers.

@smalleni would a Foreman host variable (editable by users in the UI or hammer CLI) be adequate?

You could set something like ```uc_choice: c01-h01-r620.example.com``` and if it's not false it will extrapolate that string and pick that as your undercloud (assuming it's one of your assigned hosts).

**Comment by sadsfae** [comment]
Update here per our bi-weekly DevOps call - we will simply use the ```undercloud: true/false``` host parameter here to exclude **any** host that has this from the generated ```instackenv.json``` file.

This has two main benefits:

- Lets users pick their undercloud or swap it for another host if needed (set in Foreman)
- lets users exclude machines to use for other purposes (e.g. standalone ceph).

**Comment by sadsfae** [comment]
We're going to rework this a bit, we currently have a Foreman host parameter called ```nullos: true/false``` and this does mostly the same thing we just need to rework the logic behind it.

The idea is that if you set ```nullos: false``` on any of your hosts they will have some playbooks run that swap the PXE order back to Foreman and remove them from the ```instackenv.json```.

You are then free to use that host (or hosts) as your undercloud any anything else.
