### ISSUE TITLE
omit broken hosts from wiki spare pool, move broken_state flags to mongo

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#310]
* QUADS version (`rpm -qa | grep quads` and/or `quads-cli --version`): latest
* Python version: latest 
* Operating System: current

**Describe the bug**
I have not investigated root cause but hosts that have broken_state set to true are still showing up in the "cloud01" list and users think there are available hosts.  This might be related to the host variable being a string in some cases and a boolean in other cases. 

**To Reproduce**
1. Go to '...'  See prod wiki.  We have hosts in this state currently.

**Comment by grafuls** [comment]
We don't have any logic in place to discriminate hosts in broken state from being listed as cloud01 though they would not be available for scheduling.
We should also be consistent in the way we mark this as faulty in Foreman (boolean or string), for that matters we could consider having quads do the task by adding functionality to the cli in the lines of `--mark-broken`, `--unmark-broken`, `--list-broken`.
Let me know what you guys think and we can move this one to an RFE.

**Comment by sadsfae** [comment]
This is already working as intended but would be a good RFE I think, we refer to `cloud01` or spare pool to gauge general availability.

**Comment by sadsfae** [comment]
Part of this is (moving broken_state to Mongo) satisfied via:

https://github.com/redhat-performance/quads/commit/c40ba654567a8e4c2278ab18c7a88fdaa1ed3c10

**Comment by grafuls** [comment]
Resolved here:
https://review.gerrithub.io/c/redhat-performance/quads/+/523195
