### ISSUE TITLE
[Bug]GracefulRestart not a valid option for G14 Dells

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#311]
* Python Version:
* Operating System: Fedora 30
* Target System Type: Generation 14 Dell's
* IPMI / Out-of-band Firmware Version: 3.34.34.34

Currently a GracefulRestart is called during quads move and rebuild. This is not a valid call as an option:
curl -k --user "username:password" -H "Content-Type: application/json" https://mgmt-host/redfish/v1/Systems/System.Embedded.1 | python -m json.tool | grep -A7 ResetType
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7607  100  7607    0     0  22307      0 --:--:-- --:--:-- --:--:-- 22242
            "ResetType@Redfish.AllowableValues": [
                "On",
                "ForceOff",
                "ForceRestart",
                "GracefulShutdown",
                "PushPowerButton",
                "Nmi"
            ],
Need to adjust for new generation redfish calls.

**Comment by sadsfae** [comment]
Updating Redfish API calls here should also land in core/upstream badfish.

**Comment by sadsfae** [comment]
After some discussion we'll just standardize on 

```
"On",
"ForceOff",
```
