### ISSUE TITLE
[Bug] Output of --ls-interface takes order from mongo without a sort

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#313]
* QUADS version (`rpm -qa | grep quads` and/or `quads-cli --version`):quads-1.1.2-20200122.noarch
* Python version:Python 3.7.4
* Operating System:Fedora release 30 (Thirty)

**Describe the bug**
Ran command:
`quads --ls-interface --host host`
Output:
{"name": "em1", "mac_address": "<mac>", "ip_address": "<ip>", "switch_port": "xe-0/0/22"}
{"name": "em4", "mac_address": "<mac>", "ip_address": "<ip>", "switch_port": "et-0/0/8:3"}
{"name": "em3", "mac_address": "<mac>", "ip_address": "<ip>", "switch_port": "et-0/0/8:2"}
{"name": "em2", "mac_address": "<mac>", "ip_address": "<ip>", "switch_port": "xe-0/0/23"}

When checking history for adding in the interface:
```
quads --add-interface em1 --interface-mac *** --interface-ip *** --interface-port xe-0/0/22 --host host
quads --add-interface em2 --interface-mac *** --interface-ip *** --interface-port xe-0/0/23 --host host
quads --add-interface em3 --interface-mac *** --interface-ip *** --interface-port et-0/08:2 --host host
quads --add-interface em4 --interface-mac *** --interface-ip *** --interface-port et-0/0/8:3 --host host
```
This caused an issue where the vlans were improperly set due to the ordering in ls-interface, causing qinq 0 to not communicate with the proper interfaces.

**Comment by sadsfae** [comment]
For temporary workarounds here, this is related:

https://review.gerrithub.io/c/redhat-performance/quads/+/485345

Once merged, you can run `verify_switchconf.py` (copy this down from master) to fix stuff until a base code fix is in place.
