### ISSUE TITLE
[RFE] Integrate Dell FC640 Blade Systems into QUADS/Badfish

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#319]
The Dell fc640 blades are different in that the static interface mappings in `idrac_interfaces.yml` can change depending on what rack the systems are in which can make their mappings different.

This RFE covers assimilating them into both the `badfish` library in QUADS but also upstream badfish.

**Ideas**

1) use static mappings with the rack name present for fc640 systems that would differ past a baseline mapping in `idrac_interfaces.yml`

e.g.

```
director_r620_interfaces:
director_fc640_interfaces:
director_fc640_b03_interfaces:
director_fc640_b04_interfaces:
```

2) Have badfish use an `re` shim that if a key/value pair has `b0x` before the `_interfaces:` part of of the string in `idrac_interfaces.yml` it uses that entry for all systems of type fc640 that are in rack `b0x`.

3) Add `fc640` to https://github.com/redhat-performance/quads/blob/master/quads/config.py#L29

**Comment by kambiz-aghaiepour** [comment]
I like it. 

I'm curious if this is purely a change that would happen in badfish?  or are we implementing the library in quads, separate from the upstream badfish code?

what about checking for "000" in the standalone vs blade portion, e.g. if the host is of the format: 
<rack>-<uloc>-000-<type>.domain 

then we know that $blade is "standalone" and we do what we are doing now.  But if the host is of the format:

<rack>-<uloc>-<blade value, e.g. b01>-<type>.domain

then we set $blade to <blade value, e.g. b01>

and then as you said we look for : 

director_fc640_$blade_interfaces:

and 

foreman_fc640_$blade_interfaces:

We are saying the same thing I think.

**Comment by sadsfae** [comment]
> I like it.
> 
> I'm curious if this is purely a change that would happen in badfish? or are we implementing the library in quads, separate from the upstream badfish code?

Both.  We use a badfish library for QUADS, but this should also land in the standalone badfish (that also pulls in the container version people use).

The changes needed will only be in badfish lib for quads, standalone badfish and the basic changes in `config.py`.

> 
> what about checking for "000" in the standalone vs blade portion, e.g. if the host is of the format:
> <rack>-<uloc>-000-<type>.domain
> 
> then we know that $blade is "standalone" and we do what we are doing now. But if the host is of the format:
> 
> <rack>-<uloc>-<blade value, e.g. b01>-<type>.domain
> 
> then we set $blade to <blade value, e.g. b01>
> 
> and then as you said we look for :
> 
> director_fc640_$blade_interfaces:
> 
> and
> 
> foreman_fc640_$blade_interfaces:
> 
> We are saying the same thing I think.

Yeah, that's cool too.  Works for me.  I think it's enough that we have one common, simple identifier for when badfish should do something different and use a non-generic set of static mappings in `idrac_interfaces.yml`.  I just picked the blade number e.g. `b03` as a short identifier for `re` to do the heavy lifting.

**Comment by sadsfae** [comment]
Possibly related-to:  https://github.com/redhat-performance/quads/issues/311
