### ISSUE TITLE
[RFE] Consider aiohttp-cache for Badfish

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#326]
**Is your feature request related to a problem? Please describe.**
Issue is related to reducing execution time for badfish actions when querying the same entrypoint multiple times like for get manager resource and reset type.

**Describe the solution you'd like**
Implementing a cache of request to the same entrypoint could increase Badfish performance. Considering the following: https://github.com/cr0hn/aiohttp-cache.

**Comment by sadsfae** [comment]
This would be a solid RFE for performance improvement.

**Comment by grafuls** [comment]
aiohttp-cache is for the server side requests. Using https://github.com/aio-libs/async_lru instead and already implemented.
