### ISSUE TITLE
[RFE] Employ Preemptive power cycle / one-time boot on tail end of validation phase

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#327]
After some discussion there is a pragmatic enhancement we can employ that might further streamline the validation process.

- After X amount of time (4hrs) perform a power off / on on systems being validated
- If a supermicro, re-apply PXE flag and power off / on
- If a Dell, perform a power off / on
- Make this a configurable option in `quads.yml` with a default of `240` minutes (4hrs).

**Comment by kambiz-aghaiepour** [comment]
Also iterate through the hosts still marked for build (at the 4 hour grace window) and do a badfish against them to force a 1-time boot into foreman mode.  This should catch the hosts that for whatever reason did not get rebooted into foreman.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/493104
