### ISSUE TITLE
Redefining a cloud when --vlan was previously used requires omitting --vlan

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#329]
If you need to redefine a cloud that has --vlan used, for example if you want to change to using --no-wipe, you cannot re-do the previously used command.  For example, suppose you have done:

quads-cli --define-cloud cloud03 --force --description "Do you even spam bro" --cloud-owner wfoster --cloud-ticket 999 --vlan 619

and now you want to do:

quads-cli --define-cloud cloud03 --force --description "Do you even spam bro" --cloud-owner wfoster --cloud-ticket 999 --vlan 619 --no-wipe

You will get the error:

['Data validation failed: VLAN 619 already in use.']

You can work around this by doing what you need as a two-step redefine:

quads-cli --define-cloud cloud03 --force --description "Do you even spam bro" --cloud-owner wfoster --cloud-ticket 999 --no-wipe

followed by:

quads-cli --define-cloud cloud03 --force --description "Do you even spam bro" --cloud-owner wfoster --cloud-ticket 999 --vlan 619 --no-wipe

It would be nice to avoid the data validation error when re-defining a cloud that already has an association with vlan_id, if you re-use the same vlan_id.

**Comment by grafuls** [comment]
Closing this as functionality required is already covered by the new `--mod-cloud` command.
