### ISSUE TITLE
VSC with --change on an allocation with public_vlan blindly redoes the last interface

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#330]
If you have an allocation defined with --vlan, and you run VSC against it, it reports nothing when the ports are configured corrected (as expected).  However if you run VSC against a cloud with a public vlan associated, and you pass --change, VSC will blindly "redo" the switch port changes even though it doesn't have to.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/494756
