### ISSUE TITLE
[RFE] functionality for quads --ls-vlan

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#332]
We need a way to know what vlans are associated with which cloud.  The vlan wiki is insufficient because it only shows you the vlan association once the cloud in question becomes active.  For future allocations with vlan associations it's virtually impossible to know what's "in use" so a new vlan association when selecting a vlan that has a future association will cause an error and it becomes a guessing game to know what to select. (unless you know the mongo magic to query for vlan associations).

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/505076
