### ISSUE TITLE
[RFE] Prioritize --ls-available return for systems not in an assignment

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#335]
This is an RFE for modifying the return of `quads-cli --ls-available` so the following is returned.

1) First return systems that match your criteria but are not currently in an assignment (currently `--schedule-start` and `--schedule-end` would match anything).

2) Return any other systems that fit the normal sorted return of `--ls-available` otherwise.

* This will help in cases where extension requests come in after we've already scheduled those systems, because they were late.
* We can pass `head -n X` where X is the requisite number of systems, forcing us to first pick systems that are not currently in assignments at the time of scheduling so they cannot conflict with any late extension requests that might eek in after we've already scheduled those systems to go elsewhere.

**Comment by kambiz-aghaiepour** [comment]
1. List hosts that are available for the requested period that are currently not in an assignment (e.g. in cloud01)
2. Following the cloud01 hosts that match, list any other systems that fit the requested dates.

^^ this?

**Comment by sadsfae** [comment]
>     1. List hosts that are available for the requested period that are currently not in an assignment (e.g. in cloud01)
> 
>     2. Following the cloud01 hosts that match, list any other systems that fit the requested dates.
> 
> 
> ^^ this?

yes, updated my initial description.

**Comment by grafuls** [comment]
We can achieve this by using an earlier `--schedule-start` like 1 hour before assignments going out(22:00):
`--schedule-start "2020-08-30 21:00"`

**Comment by sadsfae** [comment]
> We can achieve this by using an earlier `--schedule-start` like 1 hour before assignments going out(22:00):
> `--schedule-start "2020-08-30 21:00"`

That's a good intermediary suggestion, that will work.  However having QUADS present the systems not coming out of an existing assignment first will be a huge boon overall.
