### ISSUE TITLE
Do not reprovision host when it is moved into cloud01

### ISSUE THREAD

**Issue by abondvt89** [redhat-performance/quads#34]
Cloud01 is the pool of available servers.  Currently quads rebuilds those hosts when they are moved from another cloud environment.  This is unnecessary since they will be rebuilt when moved into an allocated Cloud environment.  This also prevents recovery if the machines are mistakenly taken out of an allocation.  If they aren't rebuilt going into Cloud01, then a mistaken move to Cloud01 could be corrected by simply moving the machine back to the correct Cloud environment and nothing would be lost.

**Comment by sadsfae** [comment]
This is a good suggestion.  We currently support moving machines back into another cloud without a rebuild via ```bin/move-and-rebuild-host.sh host01 oldcloud newcloud nobuild``` so this will help where:

1. A set of machines has been expired
2. There is no immediate new schedule for them
3. Data or otherwise is needed from them
