### ISSUE TITLE
RFE:  Add additional argparse --summary --detailed

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#341]
This is an RFE for adding an additional argparse to the `--summary` command which lists currently active environments.

Suggestion:

```quads-cli --summary --detailed```

Returns:

```
cloud02: Grafuls 32 (OpenStack LTA1) Ticket 12345
```
* Composition:   cloudname, cloudowner, systemcount, cloud_description, cloud_ticket
* Description field should likely be character limited to 16-20 characters as to not break page wrapping elsewhere

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/505547
