### ISSUE TITLE
[RFE] --terminate assignment early termination

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#342]
**Is your feature request related to a problem? Please describe.**
In some cases we can have the need to early terminate an assignment and for this we require to do a mod-schedule over all hosts in the cloud assignment.

**Describe the solution you'd like**
A cloud based command for early termination in the likes of:
`$ quads --terminate cloud34`

This would pick all current Schedule objects for each host and update the schedule end-date to `datetime.now`

**Comment by kambiz-aghaiepour** [comment]
This would be equivalent to:

`
cloud=cloud34
for h in $(quads-cli --cloud-only $cloud) ; do
   quads-cli --host $h --mod-schedule $(quads-cli --host $h --ls-schedule | grep $cloud | tail -1 | awk -F\| '{ print $1 }') \
       --schedule-end \"$(date +"%Y-%m-%d %H:%M")\"
done
`

I think it would be great!  Basically a "terminate now" button.

**Comment by grafuls** [comment]
Given that we are considering adding a command to counter the already existing `--extend-cloud` in the form of `--shrink-cloud`, and this argument requires to pass `--weeks` we can add a `--now` flag for this that would act as the `--terminate` command.

**Comment by sadsfae** [comment]
Looks like I opened a dupe issue, thanks for closing it.  Transporting my comment there to here:

This is an RFE for the argparse --shrink-cloud to do the inverse of what --extend-cloud does today.

e.g.
```
quads-cli ---shrink-cloud --check --cloud cloud02 --weeks 2
```

* Check should simply logger print what it would do with the proposed reduced --schedule-end range.
* This should HALT if shink would reduce the new --schedule-end range beyond date.time now (effectively nuking an assignment).

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/506771
