### ISSUE TITLE
(RFE) expanded --extend and --shrink functionality.

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#343]
This is an RFE for the argparse `--shrink-cloud` to do the inverse of what `--extend-cloud` does today.

e.g.

```
quads-cli ---shrink-cloud --check --cloud cloud02 --weeks 2
```

* Check should simply logger print what it would do with the proposed reduced `--schedule-end` range.
* This should **HALT** if shink would reduce the new `--schedule-end` range beyond date.time now (effectively nuking an assignment).

**Comment by grafuls** [comment]
Closing as duplicate for https://github.com/redhat-performance/quads/issues/342

**Comment by sadsfae** [comment]
This is not a duplicate, this does different things.

This is not a duplicate, --shrink and --terminate do different things.

(--shrink)

    Cloud-level, inverse of --extend--cloud

(--terminate)

    Align all --schedule-end to date.time = now with some checks.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/506771

**Comment by sadsfae** [comment]
Maybe this can be included with this RFE or later down the road but we were discussing one additional area of functionality that might fit well here:

- In addition to `--now` also provide the `--date YYYY-MM-DD HH:MM` command as well for both `--shrink` and `--extend` command-sets.

This should replace the current one-liner we are using when we want to shrink or grow a set of hosts by a certain `--schedule-end` date.

https://github.com/redhat-performance/quads#extending-the-schedule-of-existing-cloud-with-differing-active-schedules
