### ISSUE TITLE
Bug in schedule id assumptions

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#35]
There is currently a logic bug in ```lib/quads.py``` that makes some assumptions that the next available assignment id will always be iterative.  This can be triggered when a schedule has been removed and another net-new schedule is added.  This is a serious issue that can cause disruption/reprovisioning of an existing environment.

This seems to be manifested here:

https://github.com/redhat-performance/quads/blob/master/lib/libquads.py#L419

The keys need to be sorted and incremented instead.  We can reproduce this and a fix is forthcoming ASAP.

**Comment by smalleni** [comment]
Killed me :)
