### ISSUE TITLE
--mod-cloud doesn't work quite right with --no-wipe

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#351]
The new `--mod-cloud` parameter needs some additional work for `--no-wipe`

```
# quads-cli --mod-cloud cloud18 --no-wipe
Failed to validate data for cloud18
Could not parse wipe parameter
```

Applying `--wipe` seems to work however, just not `--no-wipe`

```
# quads-cli --mod-cloud cloud12 --wipe
Cloud modified successfully
```
```
# quads-cli --mod-cloud cloud12 --no-wipe
Failed to validate data for cloud12
Could not parse wipe parameter
```

In this case I just used MongoDB CLI to make the change for now.

`db.cloud.update({name:"cloud18"}, {$set:{wipe:false}})`

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/506966
