### ISSUE TITLE
[RFE] Post allocation hook to enable external automation

### ISSUE THREAD

**Issue by abondvt89** [redhat-performance/quads#352]
Provide a way for QUADS to call additional automation after the cloud environment has been created and verified, but before the allocation is released to end user.  External automation examples would like JetPack to deploy OpenStack or JetSki to deploy OpenShift.  QUADS would need to define what functionality and interface is needed between QUADS and the external automation for running, validating, and marking as successful.  This would need to be a very prescriptive environment as far as the types of cloud environments would be compatible with this external automation.

**Comment by grafuls** [comment]
This can now be achieved on Quads 2.0 API by querying the `assigments` endpoint and checking on `validated` and `provisioned` properties on the response.

## Query
```
curl -X 'GET' \
  'http://quads-stage.rdu2.scalelab.redhat.com:5000/api/v3/assignments/' \
  -H 'accept: application/json'
```

## Response
```
[
  {
    "active": true,
    "ccuser": [],
    "cloud": {
      "id": 4,
      "last_redefined": "Tue, 16 Jan 2024 10:45:12 GMT",
      "name": "cloud04"
    },
    "cloud_id": 4,
    "created_at": "Tue, 16 Jan 2024 10:45:29 GMT",
    "description": "QUADS 2.0 Testing",
    "id": 1,
    "notification": {
      "assignment_id": 1,
      "fail": false,
      "five_days": false,
      "id": 1,
      "initial": false,
      "one_day": false,
      "pre": false,
      "pre_initial": false,
      "seven_days": false,
      "success": false,
      "three_days": false
    },
    "owner": "grafuls",
    "provisioned": true,
    "qinq": 0,
    "ticket": "3180",
    "validated": true,
    "vlan_id": null,
    "wipe": true
  }
]
```
