### ISSUE TITLE
[RFE]  Provide a --retire option in lieu of --rm-host

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#364]
(This was originally @kambiz-aghaiepour suggestion, filing for him here)

Occasionally we might decommission systems instead of outright removing them from QUADS control and it might be useful to preserve the scheduling history and/or the interfaces or other data so it can be referenced later.

Some option like `quads-cli --retire --host host01.example.com` would help here, where it might:

* tag a `retired: yes` flag onto the hosts mongodb collection
* any host with `retired: yes` would not be schedulable or show up in the following returns:
   - not show up in `--ls-hosts` unless something like `--retired-hosts` is passed
   - not show up on wiki / visuals
   - not show up in any totals relying on `--ls-hosts`
   - not show up in `--ls-available`

If another approach involving `CloudHistory` is possible here perhaps that's ok too.

**Comment by grafuls** [comment]
Functionality is the same as for `--mark-broken`: https://review.gerrithub.io/c/redhat-performance/quads/+/505587
