### ISSUE TITLE
--ls-hosts appears to have additional characters that can cause issues with list comparisions

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#370]
latest upstream version.  Please see the following:

# quads --ls-hosts | head -1 | od -c
0000000 033   [   3   8   ;   2   1   m   e   1   6   -   h   1   2   -
0000020   b   0   1   -   f   c   6   4   0   .   r   d   u   2   .   s
 0000040   t   a   g   e   l   a   b   .   e   x   a   m   p   l   .   c
0000060   o   m 033   [   0   m  \n
0000067

This may be related to the filter output colors that were recently introduced.  The issue is that when comparing the host list with an external list, there needs to be some way to have "clean" output that avoids the additional terminal color coding output.

**Comment by wereii** [comment]
We should probably check for `sys.stdout.isatty()` to drop color codes for non-terminal outputs.

**Comment by sadsfae** [comment]
This was resolved some time ago, closing.
