### ISSUE TITLE
[RFE] CLI & API abstraction and re-structuring

### ISSUE THREAD

**Issue by wereii** [redhat-performance/quads#381]
### Problem/s
- Right now most of the Quads functionality resides in `bin/quads-cli` and it's all in one big function (1.6k lines long)  - for the sake of better readability and navigation this should be restructured and possibly slightly taken apart (abstracted)
- CLI depends on API - this works for the sake of DRY but in other way it's just a very cumbersome function call with http on top of it, not to mention the API code basically can't be unit tested in a normal way

This RFE is supposed to pave an easier way for both moving from CherryPy to Flask and Quads unit testing.

#### CLI

```py

class QuadsCli:
  logger: logging.Logger
  cli_args: dict

  def __init__(self, logger):
    self.logger = logger

  def run(self, cli_args: dict) -> Optional[int]:
    """
    Invokes the proper action from supplied cli args
    
    Actions can optionally return their own exit code
    NOTE: This should eventually be replaced by proper set of Exceptions, eg.:
      - CliException -> Missing or invalid arguments to program invocation, errcode == 126
      - QuadsException and subclasses -> Functionality error, "something cannot be done", errcode == 2
      - Any other exception or failure will print full stacktrace and return errcode == 1
      This is just an example and not final
    """
    self.cli_args = cli_args
   
    if cli_args.get("action"):
      # universal call for all actions stored in "action" cli argument
      action_method = getattr(self, "action_" + cli_args["action"])
      return action_method()    
    
    # Actions with params
    if self.cli_args.get("cloudresource"):
       return self.action_cloudresource()

    if self.cli_args.get("modcloud"):
      return self.action_modcloud()
    # ...

  # Helpers

  @staticmethod
  def _confirmation_dialog(msg: str, default="n") -> bool:
    return (input(msg) or default).lower() == "y"

  # Actions

  def action_retired(self):
    # do your thing, example:
    for host in retired_hosts:
      self.logger.info(host)

  def action_broken(self):
    pass

  def action_cloudresource(self):
    pass

  def action_interface(self):
    if self.cli_args["host"] is None:
      # This exception is caught by outer caller
      # exception message gets printed by log.error and returns status code 1
      raise CliException(
        "Missing option. --host option is required for --ls-interface"
      ) 
```
It might seem like I have simply converted a big function into a big class, though I think it comes with it's own benefits:

- All the logic is structured in methods which helps with navigation, quick text search with `action_N` will take you exactly to the logic of that action
- Offers the possibility to abstract subset of shared logic into helpers/static methods that are fully accessible in each action method thru `self` (the confirmation dialog is a nice example)
- _Testability_ - I can now directly invoke any action in tests or other places without having to touch/mock parsed cli args and going thru the whole if/elif chain

#### API & CLI Code dependency

Right now the solution for this is to move the current logic from API endpoints into it's own thing (`Quads` class) so that it can be reused without the whole http stack and it also comes with easy unit testing

```py
class Quads:
  def get_clouds(...) -> Sequence[Document]:
     pass
  def get_owners(...) -> Sequence[Document]:
     pass

# both CLI and API can now import this class and use the same logic anywhere
```

The API will now do only one thing and do it well - that is manage incoming http requests - validate incoming data, invoke this `Quads` abstraction and return the result as valid format (json, proper http code).

Eventually this `Quads` class should implement all the business logic of Quads (logic that shouldn't be implemented on the models itself as it is done with some now, the models are valid unit for abstraction too). 

### Summary

Main thoughts:
- split some of the existing routines into separate units so that it can be reused in other places - something along "if the same thing is done in at least two places it should be a function (or it's own unit)"
- applying dependency injection - passing "globals" thru init/s so that it can be easily mocked and customized in tests or other possible places
- try to always have one unit doing exactly one thing and doing it well (:P) 

**Though the main idea of this RFE right now is to just take existing logic and restructure it into self-contained classes.**
Without touching much of the real logic to not create too much bugs with this move.

Eventually, with time the existing code should be inspected more carefully and if possible taken apart even more (if it's possible and sane) to reduce repeated code (thus reduce the overall amount of code needed to be read and maintained). 
Again, this is more of a next step because it requires careful inspection of the multiple actions and finding some of their least common denominators that can be moved away into it's own methods/helpers and reused.

The final outcome should be having all the main, bussiness logic of Quads structured in it's own things be it `class Quads` or within models and have other things use them when needed (CLI, API, tests).
Like this, eventually if some of the CLI logic is needed in API it's as easy as creating new endpoint and calling whatever method is already implemented on the `Quads` class used by others/CLI, same goes the other way.

**Comment by sadsfae** [comment]
This is implemented in https://review.gerrithub.io/c/redhat-performance/quads/+/532623 and https://github.com/redhat-performance/quads/commit/7a6c978b57130a977b128306eef062f2315dde5f
