### ISSUE TITLE
[RFE] Change validate_env to include a one time boot to Foreman nic if provision fails

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#394]
With some of the OStree based OS's there is an issue where disk metadata is not being properly wiped and is requiring a second reboot (whether through badfish / GUI) and second one-time boot to pxe interface (foreman) which then properly provisions through anaconda. 

suggest changing to allow this in validate_env.py 
if the host is still in build state and has no ssh connection to then issue the (reboot / pxe to foreman) as part of the process 

this should also work for other use cases where the install / provision hangs requires manual intervention.

**Comment by sadsfae** [comment]
@QuantumPosix @grafuls we seem to already be doing this here in `validate_env.py`

https://github.com/redhat-performance/quads/blob/master/quads/tools/validate_env.py#L142

In case of ALIAS systems, I wonder what's keeping this from trying, should we be clearing jobs first?

**Comment by grafuls** [comment]
The way VE works is by first collecting all hosts that are still marked for build in Foreman and runs a netcat cmd against port 22. If the port is not open we assume that the host is either booting or stuck on the provisioning so we do skip the host and we let it be handled by the subsequent cron task execution for VE.
If port 22 is open we assume the host is running the OS already so we go ahead and we send the boot-to-foreman cmd via Badfish if supported.
We can check if the is_supported method is working correctly but this ticket should be moved from RFE to BUG if that's the case.

**Comment by QuantumPosix** [comment]
The proper disk wipe mechanic was achieved with new  foreman templates changes that are currently in place which fixes this issue.
