### ISSUE TITLE
[BUG] Selecting rows marked w/warning class on available GUI

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#395]
* QUADS version (`rpm -qa | grep quads` and/or `quads-cli --version`): quads-1.1.5-20210906.noarch

**Describe the bug**
On the available GUI, the rows marked with warning class in yellow, when being selected by clicking them, do not change the background to show selected as the rest of the rows.

**To Reproduce**
1. Create an assignment with current dates to end on the next available Sunday.
2. Go to Available GUI site
3. Click on a yellow row if any, otherwise 
4. See the row doesn't change the background color

**Expected behavior**
The selected warning row changes the background colour as the rest of the rows.

**Comment by sadsfae** [comment]
@grafuls not sure this is still an issue or not since the move to 2.0?

**Comment by grafuls** [comment]
This is already resolved on 2.0
