### ISSUE TITLE
[RFE] Add --omit-cloud argparse to --add-schedule and --ls-available

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#396]
This is an RFE to add support for `--omit-cloud` for the `quads-cli --add-schedule` and `--ls-available` commands.

- If `--omit-cloud cloud02` is entered then `--add-schedule` will not try to schedule any system that **would be coming** out of the _then_ cloud02.
- If `--omit-cloud` is used with `--host-list` or `--add-schedule` it should also print a stdout warning that it is omitting a certain host because it is currently a member of the said cloud _(at that time in the present upon scheduling for the future)_ that you want to omit.
- `--ls-available` will not list any hosts that are currently part of the cloud used via `--omit-cloud`

The reasoning for this RFE is that is saves time when we want to future schedule a bunch of hosts that according to `--ls-available` will show them available in the future, but they likely will get extended.  Currently we don't have an easy way to sort this.

This will also let us quickly schedule without fear of utilizing systems from current clouds that in the future will likely be extended or be used.

**Comment by kambiz-aghaiepour** [comment]
Is the idea of making --omit-cloud co-operate with --add-schedule to ensure the "free" systems (for the time of the schedule) are not allocated to cloudXX with the termination date == start date of the new schedule being added?  Wouldn't you already not select such systems if you operate --omit-cloud in conjunction with --ls-available?

**Comment by sadsfae** [comment]
> Is the idea of making --omit-cloud co-operate with --add-schedule to ensure the "free" systems (for the time of the schedule) are not allocated to cloudXX with the termination date == start date of the new schedule being added? Wouldn't you already not select such systems if you operate --omit-cloud in conjunction with --ls-available?

Yes normally if one only used `--ls-available` every time but having it in `--add-schedule` does provide a safeguard from lists generated by the UI or given by others without us having to double-check it.
