### ISSUE TITLE
[BUG] Misleading output when trying to add a schedule to non-existent host

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#398]
```
# quads --host myhost.example.com --add-schedule --schedule-start '2022-01-16 22:00' --schedule-end '2023-01-01 22:00' --schedule-cloud cloud34
Error: 'NoneType' object has no attribute 'broken'

```

The expected output should be a message indicating that `myhost.example.com` is undefined.

**Comment by sadsfae** [comment]
@kambiz-aghaiepour I believe this may have been resolved in https://review.gerrithub.io/c/redhat-performance/quads/+/533211 can you confirm?
