### ISSUE TITLE
[RFE] Simplify switch configs using a commong QinQ apply-groups

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#399]
This is very much specific to the juniper configurations.  The following needs to be tested:

```
set groups QinQ interfaces <*> flexible-vlan-tagging
set groups QinQ interfaces <*> input-native-vlan-push disable
set groups QinQ interfaces <*> mtu 9216
set groups QinQ interfaces <*> encapsulation extended-vlan-bridge
set groups QinQ interfaces <*> unit 0 vlan-id-list 1-4000
set groups QinQ interfaces <*> unit 0 input-vlan-map push
set groups QinQ interfaces <*> unit 0 output-vlan-map pop
```

Use a common QinQ apply-group definition as shown above, and move the native vlan under the specific interface being changed.  This will avoid the plethora of definitions currently being used to support each individual vlan.  Once this is tested, a PR will be generated.

**Comment by sadsfae** [comment]
Following up on this, I believe we tried this (and even reached out to Juniper too) and this is just not possible and doesn't work.  If this isn't the case please re-open but I'm going to close this otherwise.
