### ISSUE TITLE
[RFE] Provide Disk Count, Size and Type filters for ls-available UI (quads-web)

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#411]
This is an RFE to provide an optional filter for systems disk count, size and type based on collected metadata of systems.

This should leverage the `--filter` functionality tied into `--ls-hosts` and `--ls-available`

Some considerations:

1) Disk Type (SSD, NVMe, SATA) or whatever lshw has collected so far as main categories
2) Disk Count
3) Disk Size (Free form sanitized integer <= ? ) 

UX considerations should be pragmatic and open to creative discretion.

**Comment by grafuls** [comment]
This can be looked after we move to the new API as the data used on the available UI comes from a flat file.

**Comment by sadsfae** [comment]
Closing this as we already have this in place in QUADS 2.0.
