### ISSUE TITLE
[RFE] Provide a No-Op list for Move and Rebuild Network Automation

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#412]
This RFE covers adding a key/value pair omission list for `quads/tools/move_and_rebuild_hosts.py` to not perform the network automation portions of a QUADS move via https://github.com/redhat-performance/quads/blob/master/quads/tools/move_and_rebuild_hosts.py#L26.  

This would come in the following forms:

1) Moving *to* certain destination clouds
2) Partial hostnames or domain names of hosts

e.g in file `conf/quads/yml`

```
omit_network_move:  cloud14, f02-h01-000-r650.example.com, tng.example.com
```

* We'd still want other M&R functionality to occur (provisioning, update of host/cloud object fields, IPMI RBAC, Foreman RBAC etc).

Somewhere around here might be a good entrypoint to omit this:  https://github.com/redhat-performance/quads/blob/master/quads/tools/move_and_rebuild_hosts.py#L26

**Comment by k3nd1k** [comment]
This can be closed. Should be fixed with [this commit](https://github.com/redhat-performance/quads/commit/3d2980f2a444e4b67d4b45ef2d08ffa2efa75405), seems I forgot the `closes` part in the commit message.

**Comment by sadsfae** [comment]
Closed in https://github.com/redhat-performance/quads/commit/3d2980f2a444e4b67d4b45ef2d08ffa2efa75405 per @k3nd1k
