### ISSUE TITLE
quads-cli --cloud-only --cloud <cloud name> also seems to include retired hosts

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#431]
* QUADS version (`rpm -qa | grep quads` and/or `quads-cli --version`): QUADS version 1.1.7 gaúcho
* Python version: Python 3.7.4
* Operating System: fedora-release-29-7.noarch

**Describe the bug**
Looked for available hosts using : quads-cli --cloud-only --cloud cloud01

I noticed a lot of retired hosts in the output.  The output should not include retired hosts.

**Comment by grafuls** [comment]
The retired hosts are going to still be living in cloud01 (Theoretically) unless we would like to have a separate "Boneyard" cloud where to put those. Also, by definition no other cloud would have a retired host on it so this only applies for cloud01.  That filtering is in fact done automatically with `--ls-available` which is the one cmd we should encourage users to use over `--cloud-only` when looking for hosts for new assignments.
The `--filter` option was added to this command as well so you can workaround this with the following:
```bash
quads --cloud-only --cloud cloud01 --filter "retired==False"
```

**Comment by grafuls** [comment]
I would keep showing retired and broken hosts on `--cloud-only` with a red output on cli and otherwise using `--filter`.
`--ls-available` with no other parameters behaves as `--cloud-only cloud01` in the sense that it will show you any available hosts now.

**Comment by kambiz-aghaiepour** [comment]
using --filter is fine if it's already available.  How would it be used with --cloud-only ?  Or can we add --no-broken and --no-retired ?

**Comment by sadsfae** [comment]
> using `--filter` is fine if it's already available. How would it be used with `--cloud-only` ? Or can we add `--no-broken` and `--no-retired` ?

I think you don't need to worry about it now for retired hosts as as retired is filtered by default unless you specify otherwise per https://github.com/redhat-performance/quads/commit/02bbf1889cf65e22739fabba952f83914f64e31f#diff-d297153dd15d8122882150128a327e8ef36337775b1a38c9822c96c102d2d93aR1731

Broken hosts show up in `cloud01` with `--cloud-only` still but you can apply the filter to omit them with `--filter "broken==false"`

```
# quads-cli --ls-broken | grep r640
f32-h15-000-r640.example.com
```

```
# quads-cli --cloud-only --cloud cloud01 | grep f32
f32-h15-000-r640.example.com
```

Now with `--filter`

```
quads-cli --cloud-only --cloud cloud01 --filter "broken==false" | grep f32

```
