### ISSUE TITLE
quads-cli --ls-available --cloud-only --cloud cloud0X suggest unavailable hosts

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#432]
Passing `--cloud-only --cloud $SOMECURRENTCLOUDEXPIRING` is suggesting hosts that already have schedules on them that conflict.

```
quads-cli --ls-available --schedule-start "2023-03-05 22:00" --schedule-end "2023-03-19 22:00" --filter "model==R650" --cloud-only --cloud cloud26
```

**Comment by grafuls** [comment]
I don't recall having this functionality, passing `--cloud-only` to `--ls-available` neither I can see any reference of it on the code base. I believe this would rather be an issue only with `--ls-available` showing bad results. Will look into it.
