### ISSUE TITLE
[RFE] Safeguard from defining two hosts with the same data

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#444]
For all versions, I don't believe there is currently anything that would prohibit from having the following conditions met:

`quads-cli --host host1.example.com --interface-name em1 --interface-mac <MAC1> --interface-ip <IP1> --interface-port <PORT1>`

and 

`quads-cli --host host2.example.com --interface-name em1 --interface-mac <MAC2> --interface-ip <IP2> --interface-port <PORT2>`

The following conditions need to be met:

When defining interface-mac for host2, ensure `MAC2` has not been previously associated with another interface (i.e. if `MAC2 == MAC1` for all other interfaces across all existing hosts, report an error and disallow defining the interface where the MAC address is currently defined elsewhere.

Ensure that the `IP2+PORT2` combination is unique and has not been previously used for another host (two interfaces cannot be connected to the same switch port).

**Comment by sadsfae** [comment]
@grafuls @kambiz-aghaiepour let's be sure this still exists after the move to Postgres as MongoDB is an entirely different beast.
