### ISSUE TITLE
[RFE] Create Python Requests Mock Testing for Foreman API

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#454]
This RFE covers creating Python Requests monkeypatch returns for Foreman API calls that QUADS makes so we can achieve 90% testing coverage, related: https://github.com/redhat-performance/quads/issues/453

**Comment by grafuls** [comment]
This has already been resolved here:
https://github.com/redhat-performance/quads/blob/flaskapi_v3/tests/tools/test_foreman.py
