### ISSUE TITLE
[RFE] Unified Documentation Update for 2.0.0

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#465]
* ~~Updated APIv3 documentation~~
* Updated sub-command references
* Updated Wiki setup docs (simplification, XMLRPC methods are now included)
* Updated setup tasks
* Anything else we might be missing
* Test and document migration from 1.1 -> 2.0 to include importing new hosts into Postgres

**Comment by grafuls** [comment]
Updated APIv3 documentation:
https://review.gerrithub.io/c/redhat-performance/quads/+/1176489
