### ISSUE TITLE
[RFE] Remove python3-flask-bootstrap dependency.

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#470]
This covers removing dependencies on the `python3-flask-bootstrap` package which doesn't seem to be maintained in Fedora any more since version 39.

We should look to simply host static JS and CSS assets from within the repo to also relinquish the need for contacting external CDNs for them too.

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1194040
