### ISSUE TITLE
[RFE] Migrate Wiki from Wordpress to quads-web service

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#475]
**Is your feature request related to a problem? Please describe.**
With the already existing quads-web service which is serving a flask application, we can include the wiki pages here as there are only 5 pages that would have to be adapted and that could be dynamically populated with the latest quads api.

**Describe the solution you'd like**
All pages on the wordpress wiki to have there equivalent on the quads-web flask instance.

**Comment by sadsfae** [comment]
Related WIP Gerritt Patchset:  https://review.gerrithub.io/c/redhat-performance/quads/+/1201417
