### ISSUE TITLE
Implement system-level automated validation

### ISSUE THREAD

**Issue by jtaleric** [redhat-performance/quads#48]
It would be great if QUADs could ship with a ramdisk that did the host validation (ping, etc) and nuked the previous tenant's data/partitions on the disks. Rather than laying a OS on the disk to validate things.

**Comment by kambiz-aghaiepour** [comment]
I would add that since currently we have only tested using foreman as the provisioning backend for QUADS, this is more of a foreman configuration issue.  That being said I would not be opposed to having an option that could be enabled to do a netboot as opposed to a rhel7 image installation.  Typically the undercloud will need to be wiped and reinstalled though.

**Comment by sadsfae** [comment]
Foreman supports [booting from an image instead](https://theforeman.org/media.html#Buildyourownimage:Foremandiscoveryplugin-LukasZapletal) of needing to kickstart an OS, that's not very difficult to do.

**Comment by akrzos** [comment]
+1 to using a ramdisk rather than pushing customization down "rhel-devops" down to the end customer.

**Comment by jtaleric** [comment]
@kambiz-aghaiepour It would be great if you guys had a playbook that would create the centos/rhel image which would contain a tool set for validation.

It would also be cool if we could have a "Debug Ramdisk".

**Comment by sadsfae** [comment]
We will leave this as a 1.0 milestone for now, but there is one issue here in that if it doesn't PXE to re-deploy the OS (achieving the same thing) it will not PXE to boot to a ramdisk.

I think a better approach is to call racadm to wipe the disks, and something equivalent for the supermicros achieving the same thing.  The real issue here is sometimes things fail to PXE in which case nothing PXE-based would work.

On this note we can put more checks in to make sure PXE actually fires off in the first place.

**Comment by sadsfae** [comment]
We're going to be implementing a further automated validation check using the [Foreman API](https://theforeman.org/api/1.10/apidoc/v2/hosts.html), this will achieve what we're after here pretty much in that if a machine fails to PXE (and subsequently reprovision to wipe disk with the new OS) we can detect against it and gate against validation succeeding.

We should get alerted for this like we do for network failure validation so users should not get machines without a new/clean OS on it (and disks wiped).

(API Call)
```
GET /api/hosts/:id/status/:type
```

**Comment by sadsfae** [comment]
Adding here, we have an RFE in Foreman to add build status information from Hammer CLI - this will make the integration/checks here pretty easy.  We could also implement this in Python as well using the http library and checking against the existing API.

http://projects.theforeman.org/issues/20187

**Comment by sadsfae** [comment]
Example curl output from API:

```
# curl -k https://foreman.rdu.openstack.engineering.example.com/api/hosts/593/ -u cloud04:PASSWORD
```
```
{"ip":"10.12.70.116","environment_id":1,"environment_name":"production","last_report":null,"mac":"0c:c4:7a:6f:34:80","realm_id":null,"realm_name":null,"sp_mac":null,"sp_ip":null,"sp_name":null,"domain_id":1,"domain_name":"rdu.openstack.engineering.example.com","architecture_id":1,"architecture_name":"x86_64","operatingsystem_id":1,"operatingsystem_name":"RHEL 7","subnet_id":34,"subnet_name":"provisioning","sp_subnet_id":null,"ptable_id":80,"ptable_name":"generic-quick-lvm-rhel7-1disk-SMC","medium_id":9,"medium_name":"RHEL local","build":false,"comment":"","disk":"","installed_at":"2017-07-09 22:36:37 UTC","model_id":6,"hostgroup_id":23,"owner_id":3,"owner_type":"User","enabled":true,"puppet_ca_proxy_id":1,"managed":true,"use_image":null,"image_file":"","uuid":null,"compute_resource_id":null,"compute_resource_name":null,"compute_profile_id":null,"compute_profile_name":null,"capabilities":["build"],"provision_method":"build","puppet_proxy_id":1,"certname":"c04-h21-6048r.rdu.openstack.example.com","image_id":null,"image_name":null,"created_at":"2016-09-16 06:11:47 UTC","updated_at":"2017-07-09 22:36:38 UTC","last_compile":"2017-03-21 17:32:23 UTC","global_status":0,"global_status_label":"Warning","puppet_status":0,"model_name":"SSG-6048R-E1CR36H","configuration_status":0,"configuration_status_label":"No reports","build_status":0,"build_status_label":"Installed","name":"c04-h21-6048r.rdu.openstack.engineering.redhat.com","id":593,"hostgroup_name":"prov-c04","hostgroup_title":"prov-c04","parameters":[{"id":218,"name":"jbod","value":"false"},{"id":122,"name":"nullos","value":"true"}],"interfaces":[{"id":1127,"name":"c04-h21-6048r.rdu.openstack.engineering.redhat.com","ip":"10.12.70.116","mac":"0c:c4:7a:6f:34:80","identifier":"enp5s0f0","primary":true,"provision":true,"type":"interface"}],"puppetclasses":[],"config_groups":[],"all_parameters":[{"id":218,"name":"jbod","value":"false"},{"id":122,"name":"nullos","value":"true"}],"all_puppetclasses":[],"permissions":{"view_hosts":true,"create_hosts":false,"edit_hosts":true,"destroy_hosts":false,"build_hosts":true,"power_hosts":true,"console_hosts":true,"ipmi_boot":false,"puppetrun_hosts":false}}
```

In particular this JSON response is probably what we are after

```
"updated_at":"2017-07-09 22:36:38 UTC"
```

Continuing to hack on this and get the right response, then we can use the http library in Python.

**Comment by sadsfae** [comment]
Update here: querying as the individual cloud user here will limit our scope to just the machines in that assignment purview which is what we want.

We can query for build status true/false easily now, we should have enough to build this into a python http query, test and submit a patch.
```
# curl -X GET -s -k -u cloud04:PASSWORD https://foreman.rdu.openstack.engineering.example.com/api/v2/hosts?search=build=true | python -mjson.tool
```
{
    "page": 1,
    "per_page": 1000,
    "results": [
        {
            "architecture_id": 1,
            "architecture_name": "x86_64",
            "build": true,
            **"build_status": 1,**
            "build_status_label": "Pending installation",
            "capabilities": [
                "build"
            ],
            "certname": "c07-h25-6048r.rdu.openstack.engineering.example.com",
            "comment": "",
            "compute_profile_id": null,
            "compute_profile_name": null,
            "compute_resource_id": null,
            "compute_resource_name": null,
            "configuration_status": 0,
            "configuration_status_label": "No reports",
            "created_at": "2016-08-11 10:07:17 UTC",
            "disk": "",
            "domain_id": 1,
            "domain_name": "rdu.openstack.engineering.example.com",
            "enabled": true,
            "environment_id": 1,
            "environment_name": "production",
            "global_status": 0,
            "global_status_label": "Warning",
            "hostgroup_id": 20,
            "hostgroup_name": "prov-c07",
            "hostgroup_title": "prov-c07",
            "id": 556,
            "image_file": "",
            "image_id": null,
            "image_name": null,
            "installed_at": "2017-07-09 23:12:47 UTC",
            "ip": "10.12.70.140",
            "last_compile": "2017-04-04 15:39:11 UTC",
            "last_report": null,
            "mac": "0c:c4:7a:6f:32:e8",
            "managed": true,
            "medium_id": 9,
            "medium_name": "RHEL local",
            "model_id": 6,
            "model_name": "SSG-6048R-E1CR36H",
            "name": "c07-h25-6048r.rdu.openstack.engineering.example.com",
            "operatingsystem_id": 1,
            "operatingsystem_name": "RHEL 7",
            "owner_id": 3,
            "owner_type": "User",
            "provision_method": "build",
            "ptable_id": 66,
            "ptable_name": "generic-rhel7",
            "puppet_ca_proxy_id": 1,
            "puppet_proxy_id": 1,
            "puppet_status": 0,
            "realm_id": null,
            "realm_name": null,
            "sp_ip": null,
            "sp_mac": null,
            "sp_name": null,
            "sp_subnet_id": null,
            "subnet_id": 34,
            "subnet_name": "provisioning",
            "updated_at": "2017-08-02 09:43:42 UTC",
            "use_image": null,
            "uuid": null
        }
    ],
    "search": "build=true",
    "sort": {
        "by": null,
        "order": null
    },
    "subtotal": 1,
    "total": 13
}
