### ISSUE TITLE
Validate Environment Progress can exceed 100% in some cases

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#480]
In QUADS 2.0.0 as of `quads-dev-2.0.0-20240611.noarch` the validate-env phase of validating can sometimes yield progress greater than 100%.

![Screenshot_2024-06-11_15-56-51](https://github.com/redhat-performance/quads/assets/3940978/09e2b5c1-ea02-4dbb-a24c-69b81becd9d2)

One possibly related aspect here is that mid-provisioning we removed and retired several systems and that might be a contributing factor to the miscalculation.

**Comment by sadsfae** [comment]
This is really obscure, closing this as it's due to removing systems and retiring them before the automation finishes validation.

**Comment by grafuls** [comment]
This is really a corner case that we might not see in production.
This occurs only when we shrink 1 one of the host schedules to remove from the assignment after the host has already moved to the new cloud. This action would trigger a return of the host from the cloud he was assigned to, back to `cloud01` . If then the wiki regeneration get triggered before M&R does, then the wiki regen calculates the percentage by the number of hosts assigned to that cloud over the current schedules which in this case would be more than the number of hosts still on that cloud.
https://github.com/redhat-performance/quads/blob/master/quads/tools/create_input_assignments.py#L87
