### ISSUE TITLE
[BUG] Validating progress bar should be yellow instead of blue 100%

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#490]
Minor cosmetic issue but our validating status should show as red or yellow instead of blue / 100% like a released cloud when Validation is still in progress/pending.

I also recall that it was 99% instead of 100% when in validating and less than 99% when M&R was not finished, so perhaps this explains the color change:

![Screenshot_2024-06-14_17-39-55](https://github.com/redhat-performance/quads/assets/3940978/54f02425-1868-426c-a2ed-dbe24a19d021)

Compare this to here we had color coding depending on percent of progress like less than or equal to 25% (still in M&R) would be red and 50% to 99% was still validating

![Screenshot_2024-06-14_17-42-10](https://github.com/redhat-performance/quads/assets/3940978/2c77c8c5-83eb-49c1-a5d4-86433b0ffa7d)

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196408
