### ISSUE TITLE
[BUG] Public VLANS may not be releasing from QUADS or updating Wiki correctly

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#491]
It appears that at least according to QUADS `--ls-vlan` that old VLANS are not being released when the assignment expires:

Below, `cloud02` was already expired some time ago.

```
[root@quads2-stage tools]# quads --ls-vlan
619: cloud02
620: cloud03
```
```
[root@quads2-stage tools]# quads --summary
cloud01: 1 (Spare Pool)
cloud03: 14 (QUADS2 Beta Test8)
```

**Comment by sadsfae** [comment]
It appears later the VLANS did release (on wiki but not quads) but there may be a bug in our Python `logger` and thus any reliance on the private VLAN increment code which the automation is relying on which in turn does not update *new* vlan ownership because it can't find it.  GW

**Comment by sadsfae** [comment]
Yeah, still not releasing according to QUADS, though `cloud03` in this does (according to QUADS, not the wiki) show proper ownership of `cloud03` VLAN620, however `cloud02` should not own any VLAN because it's not active so it's not releasing:

```
[root@quads2-stage quads]# quads --ls-vlan
619: cloud02
620: cloud03
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196403
