### ISSUE TITLE
Wiki Updates not showing correct cloud expiration and VLAN ownership on QUADS 2.0.0

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#493]
It appears our wiki generation is showing incorrect cloud expiration times:

```
[root@quads2-stage quads]# quads --ls-schedule --host f36-h21-000-r640.example.com
Default cloud: cloud01
Current cloud: cloud05
Current schedule: 168
168| start=2024-06-18T10:45, end=2024-07-02T22:00, cloud=cloud05
```
```
[root@quads2-stage quads]# quads --ls-schedule --host f18-h31-000-1029p.example.com
Default cloud: cloud01
Current cloud: cloud05
Current schedule: 169
169| start=2024-06-18T10:45, end=2024-06-29T22:00, cloud=cloud05
```

I would expect for all systems to show **2024-07-02** except for the **f18-h31** host which had their schedule manually reduced to **2024-06-29 22:00**

![Screenshot_2024-06-18_13-41-00](https://github.com/redhat-performance/quads/assets/3940978/35223010-d05a-4535-9f46-d55141871b94)

It also appears (on the wiki side) that VLAN ownership isn't being updated properly
```
[root@quads2-stage quads]# quads --ls-vlan
619: cloud05
620: Free
```

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1196428
