### ISSUE TITLE
Issue - start date is being allowed to be set to a value that is after the end date 

### ISSUE THREAD

**Issue by QuantumPosix** [redhat-performance/quads#507]
* QUADS version (`rpm -qa | grep quads` and/or `quads --version`): quads-1.1.8-20240130.noarch
* Python version: Python 3.11.8
* Operating System: Fedora release 38 (Thirty Eight)

**Describe the bug**
When creating an new assignment, it allows you to create it with a start date that is after the end date. Implement a check to make sure the start date is before the start  date / time .

**To Reproduce**
1. Schedule assignment with command: 

quads-cli --host-list /root/utility/tickets/$ticket --add-schedule --schedule-start "2024-07-30 22:00" --schedule-end "2024-07-14 22:00" --schedule-cloud $cloud

2. Try to use mod-cloud after its created:
 -=>>quads-cli --mod-schedule --host $host --schedule-id 5 --schedule-start "2024-07-02 11:20 22:00" --schedule-end "2024-07-21 22:00"
list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/opt/quads/bin/quads-cli", line 78, in <module>
    exit_code = main(_logger=logger)
                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/quads/bin/quads-cli", line 68, in main
    return qcli.run(
           ^^^^^^^^^
  File "/opt/quads/quads/cli/cli.py", line 78, in run
    return action_meth()
           ^^^^^^^^^^^^^
  File "/opt/quads/quads/cli/cli.py", line 1330, in action_modschedule
    self.logger.info(self.quads.insert_schedule(data)["result"])
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: list indices must be integers or slices, not str


**Expected behavior**

A warning or error that displays not letting them set a start date if it is after the end date.

**Comment by sadsfae** [comment]
@QuantumPosix thanks for posting this, we will waterfall roll this into QUADS 2.0 backlog to check if this still happens there.

**Comment by QuantumPosix** [comment]
This does not happen in 2.0:

quads --add-schedule --host $host1 --schedule-start "2024-07-20 16:00"
--schedule-end "2024-07-14 22:00" --schedule-cloud cloud02
Invalid date range for start or end, start must be before end
~ Thanks,

Chris

**Comment by sadsfae** [comment]
Thanks for conforming this @QuantumPosix
