### ISSUE TITLE
instack not ordered by hostname sorting

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#511]
Generated instack metadata is not sorted by hostname, reported by @radez 

https://review.gerrithub.io/c/redhat-performance/quads/+/1199921

**Comment by grafuls** [comment]
https://review.gerrithub.io/c/redhat-performance/quads/+/1199921

**Comment by sadsfae** [comment]
@radez @jtaleric re-opening this issue as it appears our implementation isn't quite correct.  There is no fix yet but we think we know what else needs to change more or less.  For now please modify your instack files in the order you require them, since your hosts are not changing you should only need to do this once and you can copy them to our scratch storage platform if you need it HTTP/HTTPS exposed somewhere.

**Comment by sadsfae** [comment]
@radez @jtaleric this is fixed now, am seeing proper ordering of your host entries in exported instack metadata.
