### ISSUE TITLE
[RFE] quads-web ordered links on dynamic navbar

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#525]
**Is your feature request related to a problem? Please describe.**
There is no ordering on the way that the links are displayed when being picked up by the dynamic navbar generation.

**Describe the solution you'd like**
Add some logic to the dynamic navbar generation to expect an integer prefix on the file names with the index for the order like:

```
01_this.html
02_that.html
...
nn_last.html
```

**Describe alternatives you've considered**
Alternatively we can keep the file names as are and have the dynamic bar generation look for a `.order` file with the required order for the links.

**Comment by sadsfae** [comment]
I think the ordering prefix is cleaner because we don't need to manage another file.  Also, behavior-wise if items don't have it then they can just land where they land.

**Comment by sadsfae** [comment]
This is resolved in https://github.com/redhat-performance/quads/commit/28613db6edc86252d970cebf3d54e0db4aa67ef6
