### ISSUE TITLE
visual calendar creation bug  for next month.

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#53]
In some cases when calculating the "next" month we rely on a low level date command with arguments similar to:  
    date -d "now + 1months" +%m

on months with 31 days, if you run the above you actually get 2 months out instead of the next month out.  The links on the wiki therefore show the calendar view / allocation view for 2 months out instead of the next month.

**Comment by sadsfae** [comment]
Confirmed.
