### ISSUE TITLE
[RFE] quads-web navbar generation on flask initialization

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/quads#530]
**Is your feature request related to a problem? Please describe.**
As it stands the navbar is dynamically generated with every page load which might make the load time a bit slower.

**Describe the solution you'd like**
Have the navbar to be dynamically generated on the flask app initialization instead.

**Additional context**
Something similar to the way that [flask-nav3](https://github.com/wtfo-guru/flask-nav3) plugin loads.

**Comment by sadsfae** [comment]
This is resolved here:  https://review.gerrithub.io/c/redhat-performance/quads/+/1202118
