### ISSUE TITLE
Don't allow an environment to be redefined if there are future schedules for hosts within that environment

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#54]
If there are hosts that have future schedules for a given environment, that environment should not be delete-able and/or re-define-able.   

Currently there are checks in place that prevent the deletion of an environment (see libquads / ```Quads.quads_remove_cloud() )```, but the restrictions prevent deletion for ALL schedules, even the schedules in the past.  We need to decide if this is too restrictive.  Perhaps the restriction needs to consider only future schedules for hosts?

Also ```Quads.quads_update_cloud()``` is used to define (or redefine with --force) the definition of an environment.  However it does not take into consideration the existence of future schedules.  Arguably if there are schedules in flight for the future across host resources, the environment name should not be recyclable.  Typically we re-use the environment names (cloud01, cloud02, etc) as the need to allocate host resources into an environment arises.  With multiple people doing allocations, there is a risk of using an environment that might currently have 0 hosts, but whose hosts are slated to move at some point in the future.

**Comment by sadsfae** [comment]
This would be a nice thing to enforce via quads, currently we get around this by first looking up the ticket associated with a cloud definition via ```bin/quads.py --ls-ticket``` and then looking that up in RT to see if it's completed and **then** re-using it.  This change would provide enforcement so existing future schedules would not be overwritten.
