### ISSUE TITLE
[RFE] Bring back  2.0 selection highlight and expire warning for quads-web /available

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#547]
We seem to be missing the orange'ish background when servers are free but coming from a previous environment in `/available`

This was provided in 2.0.x here:  https://github.com/redhat-performance/quads/commit/ea3ee7697026423d7545736b5034d671cbc9b644

We're also missing selection highlighting where the selection field turns blue to indicate it's been selected.

**Comment by sadsfae** [comment]
Additionally, we need a space at the bottom of `/available` page footer info area e.g.  `Showing 1 to 25 of 38 entries1 row selected` should have a space between `25 of 38 entries` and `1 row selected`

**Comment by willfoster** [comment]
WIP patchset (please amend as you want):  https://review.gerrithub.io/c/redhat-performance/quads/+/1203702

**Comment by sadsfae** [comment]
WIP patchset here (feel free to amend):  https://review.gerrithub.io/c/redhat-performance/quads/+/1203702

**Comment by sadsfae** [comment]
Fixed in https://github.com/redhat-performance/quads/commit/d094f60f5c24b99f7fb2828e5ff717783e78f0a9
