### ISSUE TITLE
RFE : Alternate color of rows

### ISSUE THREAD

**Issue by kambiz-aghaiepour** [redhat-performance/quads#6]
Alternate the color of rows, white and gray would be nice.

Add a :hover for when the mouse overs over a specific row.

**Comment by kambiz-aghaiepour** [comment]
We currently parse markdown which only provides structure and format not colors, however we can dig into the WP CSS and I think we can find a solution for this. Thanks for filing it.

**Comment by sadsfae** [comment]
re-posting this for @jtaleric

**Comment by sadsfae** [comment]
This is pretty much implemented in the heatmap side of things, I'm marking this as resolved.
