### ISSUE TITLE
RFE:  Graphical visualization of monthly machine assignments

### ISSUE THREAD

**Issue by abondvt89** [redhat-performance/quads#7]
It would be very beneficial to have a way to visualize the machine allocations by month.  This would help with planning how to meet upcoming requests for resources as well as give visual indications about which machines or sets of machines are used most often.  A different color for each quads cloud allocation with a list of machines on one axis and the days of the month on the other.

**Comment by sadsfae** [comment]
something like this might work?

![availability_calendar](https://cloud.githubusercontent.com/assets/3940978/20400446/9eeef73a-acec-11e6-8284-2a2a5c49c515.jpg)

**Comment by abondvt89** [comment]
Yes, that kind of graphical visualization would be perfect.  Machines on the left and dates on the top.
