### ISSUE TITLE
schedule.yaml contains weird values for cc_user sometimes

### ISSUE THREAD

**Issue by smalleni** [redhat-performance/quads#74]
Sometimes we see weird values like  ccusers: *id001 and  ccusers: &id003 [] in the cloud_history dictionary os schedule.yaml

**Comment by sadsfae** [comment]
This change should push us to use ```yaml.safe_load``` as is recommended [best practice](http://stackoverflow.com/questions/6866600/yaml-parsing-and-python) for dealing with PyYAML and Python.
