### ISSUE TITLE
Migrate CherryPy API to Flask

### ISSUE THREAD

**Issue by sadsfae** [redhat-performance/quads#86]
Now that we have a working [JSON API](https://github.com/redhat-performance/quads#api-get-operations) we can start to build on more advanced visuals and UI options for QUADS users.

We are currently using ```SimpleHTTPServer``` for very basic wsgi / HTTP JSON responses and GET/POST activity but anything more where we want to open things up outside the QUADS host we want to use a hardened, robust micro framework like Flask.

The first step here is to [utilize Flask](http://flask.pocoo.org/) to build a (starting with) a simple web interface where people can query backend QUADS commands and display the results.

This will pave the way to later to actually doing scheduling from a Flask UI with the proper layer of authentication but we should start with simply displaying data, schedules and other useful QUADS information in this way.

**Comment by sadsfae** [comment]
This issue has been a placeholder as we have a proper cherrypy webserver/API, it should now track our migration from cherrypy to flask.

Ultimately, all QUADS web resources can be run from flask including the wiki (wp), any request forms your organization uses, visuals and the like.

**Comment by grafuls** [comment]
A first patch for a Flask implementation in the form of quads-web sysctl service has been merged here [1].

[1] https://review.gerrithub.io/c/redhat-performance/quads/+/498781

**Comment by grafuls** [comment]
This is already done on `flaskapi_v3` branch
